import { useEffect, useState } from "react";
import { adminApi } from "../../services/adminManagementService.js";

export default function AnalyticsPage() {
  const [filter, setFilter] = useState("month");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [data, setData] = useState({ revenueGrowth: 0, userGrowth: 0, listingGrowth: 0, promotionGrowth: 0, cityPerformance: [], categoryPerformance: [] });
  useEffect(() => { adminApi.analytics({ range: filter, from: startDate, to: endDate }).then((d) => setData({ revenueGrowth: (d.listingFeeRevenue || 0) + (d.promoRevenue || 0), userGrowth: d.userGrowth || 0, listingGrowth: d.listingGrowth || 0, promotionGrowth: d.promoRevenue || 0, cityPerformance: (d.cityStats || []).map((c) => ({ name: c.city, rate: `${Math.min(100, Math.round((c.rentals / (c.listings || 1)) * 100))}%` })), categoryPerformance: d.categoryPerformance || [] })).catch(console.error); }, [filter, startDate, endDate]);
  return <main className="dashboard-content"><div className="d-flex justify-content-between align-items-center mb-4"><div><span className="section-label">SUPER ADMIN</span><h1 className="h3 mb-0">Platform Analytics</h1><p className="text-muted mb-0">Track platform KPIs, system transactions, and location metrics.</p></div></div><div className="admin-table-container mb-4"><div className="d-flex flex-wrap align-items-center justify-content-between gap-3"><div className="d-flex gap-2">{["today", "week", "month", "year"].map(opt => <button key={opt} type="button" className={`btn btn-sm ${filter === opt ? "btn-accent-custom" : "btn-outline-secondary"}`} onClick={() => setFilter(opt)}>{opt.toUpperCase()}</button>)}</div><div className="d-flex align-items-center gap-2"><span className="text-muted"><small>Custom Range:</small></span><input type="date" className="form-control form-control-sm" value={startDate} onChange={e => { setStartDate(e.target.value); setFilter("custom"); }} /><span className="text-muted"><small>to</small></span><input type="date" className="form-control form-control-sm" value={endDate} onChange={e => { setEndDate(e.target.value); setFilter("custom"); }} /></div></div></div><div className="row mb-4"><Card label="Revenue Growth" value={`+${Number(data.revenueGrowth || 0).toLocaleString()} ETB`} tone="success" /><Card label="User Growth" value={`+${data.userGrowth} Users`} tone="primary" /><Card label="Listing Growth" value={`+${data.listingGrowth} Listings`} tone="warning" /><Card label="Promotion Growth" value={`+${Number(data.promotionGrowth || 0).toLocaleString()} ETB`} tone="danger" /></div><div className="row"><div className="col-lg-6 mb-4"><div className="admin-table-container"><h2 className="h5 mb-3">City Performance Distribution</h2><ul className="list-group list-group-flush">{data.cityPerformance.map(city => <li key={city.name} className="list-group-item bg-transparent text-color border-0 py-3"><div className="d-flex justify-content-between mb-1"><span>{city.name}</span><strong className="text-danger">{city.rate}</strong></div><div className="progress" style={{ height: "6px" }}><div className="progress-bar bg-danger" style={{ width: city.rate }} /></div></li>)}</ul></div></div><div className="col-lg-6 mb-4"><div className="admin-table-container"><h2 className="h5 mb-3">Category Performance</h2><ul className="list-group list-group-flush">{data.categoryPerformance.map(cat => <li key={cat.name} className="list-group-item bg-transparent text-color d-flex justify-content-between"><span>{cat.name}</span><strong className="text-danger">{cat.count} New Listings</strong></li>)}</ul></div></div></div></main>;
}
function Card({ label, value, tone }) { return <div className="col-md-3"><div className="p-4 border rounded shadow-sm bg-white text-dark mb-3"><span className="text-muted"><small>{label}</small></span><h2 className={`mb-0 fw-bold text-${tone}`}>{value}</h2></div></div>; }
