import { useEffect, useState } from "react";
import { adminApi } from "../../services/adminManagementService.js";

export default function PlatformOverviewPage() {
  const [data, setData] = useState({ userGrowth: 0, listingGrowth: 0, bookingGrowth: 0, promoRevenue: 0, cityStats: [] });
  useEffect(() => { adminApi.analytics({ range: "month" }).then(setData).catch(console.error); }, []);
  const activeOwners = data.cityStats?.reduce((sum, c) => sum + c.listings, 0) || 0;
  return <main className="dashboard-content"><div className="d-flex justify-content-between align-items-center mb-4"><div><span className="section-label">SUPER ADMIN</span><h1 className="h3 mb-0">Platform Overview</h1><p className="text-muted mb-0">Monitor live platform traffic, engagement, and infrastructure metrics.</p></div></div><div className="row"><div className="col-lg-6 mb-4"><div className="admin-table-container"><h2 className="h5 mb-3 d-flex align-items-center gap-2"><i className="bi bi-globe text-primary-custom" /> Platform Traffic Statistics</h2><div className="row text-center mt-3"><Stat label="Total Sessions" value="-" /><Stat label="Bounce Rate" value="-" /><Stat label="Avg. Session Duration" value="-" /><Stat label="Active Users Now" value="-" danger /></div></div></div><div className="col-lg-6 mb-4"><div className="admin-table-container"><h2 className="h5 mb-3 d-flex align-items-center gap-2"><i className="bi bi-people text-primary-custom" /> User Statistics & Metrics</h2><ul className="list-group list-group-flush mt-2"><li className="list-group-item bg-transparent text-color d-flex justify-content-between"><span>Monthly New Signups</span><strong className="text-success">+{data.userGrowth}</strong></li><li className="list-group-item bg-transparent text-color d-flex justify-content-between"><span>Active Renters</span><strong className="text-color">{data.bookingGrowth}</strong></li><li className="list-group-item bg-transparent text-color d-flex justify-content-between"><span>Active Owners</span><strong className="text-color">{activeOwners}</strong></li><li className="list-group-item bg-transparent text-color d-flex justify-content-between"><span>User Retention Rate</span><strong className="text-danger">-</strong></li></ul></div></div></div></main>;
}
function Stat({ label, value, danger }) { return <div className="col-6 mb-3"><div className="p-3 border rounded"><span className="text-muted d-block mb-1"><small>{label}</small></span><strong className={`h4 ${danger ? "text-danger" : "text-color"}`}>{value}</strong></div></div>; }

