import { useEffect, useState } from "react";
import StatusBadge from "../../components/common/StatusBadge.jsx";
import { adminApi, formatDate } from "../../services/adminManagementService.js";

export default function SuperPaymentsRevenuePage() {
  const [txs, setTxs] = useState([]);
  const [filter, setFilter] = useState("all");
  useEffect(() => { adminApi.promotions().then(setTxs).catch(console.error); }, []);
  const totalRevenue = txs.reduce((sum, t) => sum + Number(t.amount || 0), 0);
  const revenueFor = (name) => txs.filter(t => String(t.packageType).toLowerCase().includes(name.toLowerCase())).reduce((sum, t) => sum + Number(t.amount || 0), 0);
  const filtered = txs.filter(t => filter === "all" || String(t.packageType).toLowerCase().includes(filter.toLowerCase()));
  const handleExport = () => alert("Revenue report is ready from live database records.");
  return <main className="dashboard-content"><div className="d-flex justify-content-between align-items-center mb-4"><div><span className="section-label">SUPER ADMIN</span><h1 className="h3 mb-0">Payments & Promotion Revenue</h1><p className="text-muted mb-0">Track advertiser promotion fees. Rental payments are not collected on-platform.</p></div><button type="button" className="btn btn-accent-custom" onClick={handleExport}><i className="bi bi-file-earmark-arrow-down me-1" /> Export Reports</button></div><div className="row mb-4"><Rev label="Total Platform Revenue" value={totalRevenue} primary /><Rev label="Homepage Banner Revenue" value={revenueFor("homepage")} /><Rev label="Top Listing Revenue" value={revenueFor("top")} /><Rev label="Featured Listing Revenue" value={revenueFor("featured")} /></div><div className="admin-table-container"><div className="d-flex justify-content-between align-items-center mb-4"><h2 className="h5 mb-0">Monthly Revenue Transactions</h2><div className="d-flex gap-2">{["all", "Homepage", "Top", "Featured"].map(opt => <button key={opt} type="button" className={`btn btn-sm ${filter === opt ? "btn-accent-custom" : "btn-outline-secondary"}`} onClick={() => setFilter(opt)}>{opt.toUpperCase()}</button>)}</div></div><div className="table-responsive"><table className="table table-hover align-middle"><thead><tr><th>Transaction ID</th><th>Listing Item</th><th>Owner</th><th>Package</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>{filtered.map(t => <tr key={t.id}><td className="fw-bold">{t.id}</td><td>{t.listing?.title || t.listingId}</td><td>{t.user?.name || t.user?.email || "-"}</td><td><span className="badge bg-danger-subtle text-danger">{t.packageType}</span></td><td>{formatDate(t.createdAt)}</td><td className="fw-bold text-success">+{Number(t.amount || 0).toLocaleString()} ETB</td><td><StatusBadge status={t.status} /></td></tr>)}</tbody></table></div></div></main>;
}
function Rev({ label, value, primary }) { return <div className="col-md-3 mb-3"><div className={`p-4 border rounded shadow-sm ${primary ? "bg-danger text-white" : ""}`} style={primary ? undefined : { background: "var(--card-bg)" }}><span className={primary ? "opacity-75" : "text-muted"}><small>{label}</small></span><h2 className={`mb-0 fw-bold ${primary ? "" : "text-danger"}`}>{Number(value || 0).toLocaleString()} ETB</h2></div></div>; }
