const ROLES = Object.freeze({
  USER: 'USER',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
});

const BOOKING_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED',
});

const PAYMENT_TYPES = Object.freeze({
  LISTING_FEE: 'LISTING_FEE',
  PROMOTION_FEE: 'PROMOTION_FEE',
});

const VERIFICATION_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
});

module.exports = {
  ROLES,
  BOOKING_STATUSES,
  PAYMENT_TYPES,
  VERIFICATION_STATUSES,
};
