const fs = require('fs');

const filePath = 'c:\\Users\\obse\\Desktop\\EASTERNCITY-rental-SYSTEM-develop\\EASTERNCITY-rental-SYSTEM-develop\\src\\data\\items.js';

let content = fs.readFileSync(filePath, 'utf8');

const newItems = `
  // ───────────── FASHION & ACCESSORIES (ADDED) ─────────────
  {
    id: "premium-wedding-gown",
    title: "Premium Wedding Gown",
    category: "fashion-accessories",
    location: "Sabian, Dire Dawa",
    city: "Dire Dawa",
    sefar: "Sabian",
    pricePerDay: 2500,
    image: canonImage,
    rating: 4.9,
    owner: "Bride's Dream",
    description: "Elegant silk and lace wedding gown. Professionally dry-cleaned after every rental.",
    features: ["Silk & Lace", "Dry Cleaned", "Size M/L", "Veil Included"],
    available: true,
    featured: false,
    status: "published",
    inquiries: 14,
    messages: 5,
    expiresAt: "2026-08-01",
    requirements: {
      documents: ["National ID"],
      minimumPeriod: "2 Days",
      age: "18+",
      conditions: "Dry cleaning cost is covered. Damage deposit required.",
    },
  },
  {
    id: "designer-handbag",
    title: "Luxury Designer Handbag",
    category: "fashion-accessories",
    location: "Aboker, Harar",
    city: "Harar",
    sefar: "Aboker",
    pricePerDay: 600,
    image: bikeImage,
    rating: 4.7,
    owner: "Chic Accessories",
    description: "Authentic designer leather handbag for evening dinners and ceremonies.",
    features: ["Genuine Leather", "Dust Bag", "Medium Size", "Gold Details"],
    available: true,
    featured: false,
    status: "published",
    inquiries: 5,
    messages: 1,
    expiresAt: "2026-07-28",
    requirements: {
      documents: ["National ID"],
      minimumPeriod: "1 Day",
      age: "18+",
      conditions: "Return in original dust bag. No liquid stains allowed.",
    },
  },
  {
    id: "classic-tuxedo-suit",
    title: "Classic Black Tuxedo Set",
    category: "fashion-accessories",
    location: "Sheedaha, Jigjiga",
    city: "Jigjiga",
    sefar: "Sheedaha",
    pricePerDay: 1200,
    image: canonImage,
    rating: 4.8,
    owner: "Gentlemen Wear",
    description: "Modern fit black tuxedo with bow tie and cuffs. Perfect for weddings and formal dinners.",
    features: ["Modern Fit", "Complete Set", "Size L", "Premium Wool"],
    available: true,
    featured: false,
    status: "published",
    inquiries: 9,
    messages: 3,
    expiresAt: "2026-07-31",
    requirements: {
      documents: ["National ID"],
      minimumPeriod: "1 Day",
      age: "18+",
      conditions: "Late return penalty applies. Ironing not required upon return.",
    },
  },
  {
    id: "gold-jewelry-set",
    title: "Traditional Bridal Jewelry Set",
    category: "fashion-accessories",
    location: "Jugal, Harar",
    city: "Harar",
    sefar: "Jugal",
    pricePerDay: 1500,
    image: catagCanonImage,
    rating: 4.9,
    owner: "Heritage Jewels",
    description: "Stunning gold-plated traditional jewelry set for cultural wedding celebrations.",
    features: ["Gold Plated", "Bridal Design", "Necklace & Earrings", "Storage Case"],
    available: true,
    featured: false,
    status: "published",
    inquiries: 18,
    messages: 6,
    expiresAt: "2026-08-10",
    requirements: {
      documents: ["National ID", "Passport Copy"],
      minimumPeriod: "1 Day",
      age: "21+",
      conditions: "Refundable security deposit is mandatory.",
    },
  },

  // ───────────── BABY & KIDS (ADDED) ─────────────
  {
    id: "infant-car-seat",
    title: "Infant Car Safety Seat",
    category: "baby-kids",
    location: "Sabian, Dire Dawa",
    city: "Dire Dawa",
    sefar: "Sabian",
    pricePerDay: 400,
    image: bikeImage,
    rating: 4.8,
    owner: "Little Safety",
    description: "Highly rated infant car seat with impact protection and easy install base.",
    features: ["Side Impact Protection", "5-Point Harness", "Easy Install", "Washable Cover"],
    available: true,
    featured: false,
    status: "published",
    inquiries: 6,
    messages: 2,
    expiresAt: "2026-07-29",
    requirements: {
      documents: ["National ID"],
      minimumPeriod: "3 Days",
      age: "No Restriction",
      conditions: "Must be returned clean. No food stains.",
    },
  },
  {
    id: "toddler-playpen",
    title: "Portable Toddler Playpen",
    category: "baby-kids",
    location: "Kebele 02, Jigjiga",
    city: "Jigjiga",
    sefar: "Kebele 02",
    pricePerDay: 300,
    image: bikeImage,
    rating: 4.6,
    owner: "Kids World",
    description: "Spacious and portable playpen with breathable mesh walls and folding travel bag.",
    features: ["Breathable Mesh", "Foldable", "Travel Bag", "Toy Pocket"],
    available: true,
    featured: false,
    status: "published",
    inquiries: 8,
    messages: 3,
    expiresAt: "2026-07-22",
    requirements: {
      documents: ["National ID"],
      minimumPeriod: "2 Days",
      age: "No Restriction",
      conditions: "Cleaned before handover.",
    },
  },
  {
    id: "wooden-baby-crib",
    title: "Wooden Baby Crib & Mattress",
    category: "baby-kids",
    location: "Amir Nur, Harar",
    city: "Harar",
    sefar: "Amir Nur",
    pricePerDay: 650,
    image: sofaImage,
    rating: 4.7,
    owner: "Sweet Dreams",
    description: "Sturdy wooden crib with height-adjustable mattress settings. Sanitized for safety.",
    features: ["Adjustable Height", "Teething Rails", "Foam Mattress", "Non-Toxic Paint"],
    available: true,
    featured: false,
    status: "published",
    inquiries: 12,
    messages: 4,
    expiresAt: "2026-08-03",
    requirements: {
      documents: ["National ID"],
      minimumPeriod: "5 Days",
      age: "No Restriction",
      conditions: "Assembly tools included. Delivery can be arranged.",
    },
  },
  {
    id: "adjustable-high-chair",
    title: "Adjustable Baby High Chair",
    category: "baby-kids",
    location: "Megala, Dire Dawa",
    city: "Dire Dawa",
    sefar: "Megala",
    pricePerDay: 200,
    image: chairImage,
    rating: 4.5,
    owner: "Baby Diners",
    description: "Height adjustable high chair with double tray and seat pad for easy feeding.",
    features: ["Double Tray", "Adjustable Height", "Wheels with Locks", "Wipeable Pad"],
    available: true,
    featured: false,
    status: "published",
    inquiries: 4,
    messages: 1,
    expiresAt: "2026-07-19",
    requirements: {
      documents: ["National ID"],
      minimumPeriod: "2 Days",
      age: "No Restriction",
      conditions: "Sanitized before return.",
    },
  },

  // ───────────── BEAUTY & SALON (ADDED) ─────────────
  {
    id: "makeup-station-led",
    title: "Portable LED Makeup Mirror & Station",
    category: "beauty-salon",
    location: "Sheedaha, Jigjiga",
    city: "Jigjiga",
    sefar: "Sheedaha",
    pricePerDay: 800,
    image: pcImage,
    rating: 4.8,
    owner: "Glamour Rental",
    description: "Compact makeup station with adjustable stand, LED bulbs, and outlets for styling tools.",
    features: ["Dimmable LED Bulbs", "Adjustable Stand", "Outlets", "Mirror Included"],
    available: true,
    featured: false,
    status: "published",
    inquiries: 10,
    messages: 4,
    expiresAt: "2026-07-31",
    requirements: {
      documents: ["National ID"],
      minimumPeriod: "1 Day",
      age: "18+",
      conditions: "Bring your own makeup tools. Clean mirrors before return.",
    },
  },
  {
    id: "foldable-massage-table",
    title: "Foldable Massage Table",
    category: "beauty-salon",
    location: "Jugal, Harar",
    city: "Harar",
    sefar: "Jugal",
    pricePerDay: 500,
    image: sofaImage,
    rating: 4.7,
    owner: "Zen Spa Rentals",
    description: "Lightweight foldable massage table with carrying bag. Ideal for home spa services.",
    features: ["Foldable", "Carrying Bag", "Height Adjustable", "Padded Leather"],
    available: true,
    featured: false,
    status: "published",
    inquiries: 11,
    messages: 3,
    expiresAt: "2026-08-04",
    requirements: {
      documents: ["National ID"],
      minimumPeriod: "1 Day",
      age: "18+",
      conditions: "Use protective sheets to prevent oil stains on the leather.",
    },
  },
  {
    id: "hair-steamer-pro",
    title: "Professional Salon Hair Steamer",
    category: "beauty-salon",
    location: "Kefira, Dire Dawa",
    city: "Dire Dawa",
    sefar: "Kefira",
    pricePerDay: 900,
    image: projectorImage,
    rating: 4.6,
    owner: "Salon Equip Co",
    description: "Professional ionic hair steamer on wheels. Ideal for deep hair conditioning treatments.",
    features: ["Ionic Steam", "Hood Adjustable", "Timer", "Rolling Base"],
    available: true,
    featured: false,
    status: "published",
    inquiries: 7,
    messages: 2,
    expiresAt: "2026-07-27",
    requirements: {
      documents: ["National ID"],
      minimumPeriod: "2 Days",
      age: "18+",
      conditions: "Use distilled water only to prevent mineral build-up.",
    },
  },
  {
    id: "shampoo-bowl-portable",
    title: "Portable Hair Shampoo Bowl",
    category: "beauty-salon",
    location: "Arategna, Harar",
    city: "Harar",
    sefar: "Arategna",
    pricePerDay: 350,
    image: bikeImage,
    rating: 4.5,
    owner: "Stylist Supply",
    description: "Adjustable height shampoo basin with drain hose for mobile hairdressers and home styling.",
    features: ["Adjustable Height", "Drain Hose", "Lightweight", "Tilt Mechanism"],
    available: true,
    featured: false,
    status: "published",
    inquiries: 5,
    messages: 1,
    expiresAt: "2026-07-23",
    requirements: {
      documents: ["National ID"],
      minimumPeriod: "1 Day",
      age: "18+",
      conditions: "Ensure hoses are thoroughly drained and dried before return.",
    },
  },

  // ───────────── MUSIC & AUDIO (ADDED) ─────────────
  {
    id: "acoustic-guitar-fender",
    title: "Fender Acoustic Guitar",
    category: "music-audio",
    location: "Amir Nur, Harar",
    city: "Harar",
    sefar: "Amir Nur",
    pricePerDay: 300,
    image: bikeImage,
    rating: 4.7,
    owner: "Melody Rent",
    description: "Rich sounding Fender acoustic guitar. Includes protective gig bag and picks.",
    features: ["Fender Brand", "Gig Bag Included", "Picks Included", "Steel Strings"],
    available: true,
    featured: false,
    status: "published",
    inquiries: 12,
    messages: 5,
    expiresAt: "2026-08-05",
    requirements: {
      documents: ["National ID"],
      minimumPeriod: "2 Days",
      age: "18+",
      conditions: "Refundable deposit of 500 ETB. Do not replace strings yourself.",
    },
  },
  {
    id: "studio-mic-set",
    title: "Shure Studio Microphone Set",
    category: "music-audio",
    location: "Legehare, Dire Dawa",
    city: "Dire Dawa",
    sefar: "Legehare",
    pricePerDay: 450,
    image: speakerImage,
    rating: 4.8,
    owner: "Podcast Pro",
    description: "High quality Shure cardioid microphone with shock mount, pop filter, and XLR cable.",
    features: ["Cardioid Pickup", "Shock Mount", "Pop Filter", "XLR Cable"],
    available: true,
    featured: false,
    status: "published",
    inquiries: 9,
    messages: 3,
    expiresAt: "2026-07-30",
    requirements: {
      documents: ["National ID"],
      minimumPeriod: "1 Day",
      age: "18+",
      conditions: "Protect from high moisture. Return inside padded case.",
    },
  },
  {
    id: "digital-keyboard-yamaha",
    title: "Yamaha 61-Key Digital Keyboard",
    category: "music-audio",
    location: "Kebele 01, Jigjiga",
    city: "Jigjiga",
    sefar: "Kebele 01",
    pricePerDay: 700,
    image: pcImage,
    rating: 4.8,
    owner: "Keynotes",
    description: "Yamaha keyboard with built-in speakers, headphone output, and adapter. Perfect for practice.",
    features: ["61 Keys", "Power Adapter", "Music Stand", "Headphone Jack"],
    available: true,
    featured: false,
    status: "published",
    inquiries: 15,
    messages: 6,
    expiresAt: "2026-08-02",
    requirements: {
      documents: ["National ID"],
      minimumPeriod: "2 Days",
      age: "18+",
      conditions: "Use clean dry hands. Keep away from water.",
    },
  },
  {
    id: "dj-controller-pioneer",
    title: "Pioneer DJ Controller Set",
    category: "music-audio",
    location: "Sabian, Dire Dawa",
    city: "Dire Dawa",
    sefar: "Sabian",
    pricePerDay: 1500,
    image: pcImage,
    rating: 4.9,
    owner: "Beats Event Sound",
    description: "Pioneer DJ controller deck with headphone, audio cables, and software access keys.",
    features: ["4-Channel", "USB Plug-in", "Headphone Out", "DJ software sync"],
    available: true,
    featured: true,
    status: "published",
    inquiries: 22,
    messages: 8,
    expiresAt: "2026-08-07",
    requirements: {
      documents: ["National ID", "Company Work ID"],
      minimumPeriod: "1 Day",
      age: "21+",
      conditions: "Damage replacement value agreement must be signed before rental.",
    },
  },
];
`;

const closingIndex = content.lastIndexOf('];');
if (closingIndex !== -1) {
  content = content.slice(0, closingIndex) + newItems + content.slice(closingIndex);
  fs.writeFileSync(filePath, content, 'utf8');
  console.log('Successfully added 16 new listings to items.js!');
} else {
  console.error('Could not find closing bracket in items.js');
}
