/* eslint-disable react-refresh/only-export-components */
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

const LanguageContext = createContext(null);

const translations = {
  en: {
    home: "Home",
    categories: "Categories",
    howItWorks: "How It Works",
    about: "About",
    contact: "Contact",
    contactUs: "Contact Us",
    items: "Search/Browse Items",
    registerLogin: "Register / Login",
    loginRegister: "Login / Register",
    dashboard: "Dashboard",
    logout: "Logout",
    profile: "Profile",
    messages: "Messages",
    language: "Language",
    footerTagline:
      "Citywide Item Rental System - trusted rentals across your city.",
    ourStory: "Our Story",
    careers: "Careers",
    privacyPolicy: "Privacy Policy",
    terms: "Terms",
    support: "Support",
    legal: "Legal",
    openMenu: "Open menu",
    heroEyebrow: "TRUSTED DEALER, RENTAL",
    heroCta: "Go To Listing",
    heroDiscountOff: "OFF",
    heroFeaturedAlt: "Featured rental item",
    heroPrevious: "Previous hero slide",
    heroNext: "Next hero slide",
    heroSlides: "Hero slides",
    heroShowSlide: "Show hero slide",
    heroVehicleTitle: "Rent Cars & Vehicles Near You",
    heroVehicleSubtitle: "Browse trusted vehicle rentals from local owners.",
    heroElectronicsTitle: "Rent Electronics For Any Occasion",
    heroElectronicsSubtitle:
      "Find laptops, speakers, projectors, gaming devices, and more.",
    heroToolsTitle: "Professional Tools On Demand",
    heroToolsSubtitle: "Rent tools and equipment without the cost of ownership.",
    heroCameraTitle: "Camera Rentals For Every Shoot",
    heroCameraSubtitle:
      "Book cameras, lenses, and kits for events, content, and creative work.",
    heroFurnitureTitle: "Furniture Rentals Made Easy",
    heroFurnitureSubtitle: "Affordable furniture rentals for homes and events.",
    heroSportsTitle: "Sports Gear Ready When You Are",
    heroSportsSubtitle:
      "Rent bikes, golf sets, kayaks, climbing gear, and outdoor equipment.",
    allItems: "All Items",
    usedItems: "Used Items",
    newItems: "New Items",
    category: "Category",
    allCategories: "All Categories",
    electronics: "Electronics",
    tools: "Tools",
    vehicles: "Vehicles",
    cameras: "Cameras",
    sports: "Sports",
    furniture: "Furniture",
    maxPrice: "Max Price",
    maxPriceTitle: "Max price per day in ETB",
    perDay: "day",
    searchRentals: "Search Rentals",
    trustedRentalService: "TRUSTED RENTAL SERVICE",
    exploreAllItems: "Explore All Items",
    allStatus: "All Status",
    featured: "Featured",
    rentalItem: "Rental Item",
    viewDetails: "VIEW DETAILS",
    compare: "Compare",
    wishlist: "Wishlist",
    similar: "Similar",
    suv: "SUV",
    camera: "Camera",
    events: "Events",
    petrol: "Petrol",
    kit: "Kit",
    cordless: "Cordless",
    likeNew: "Like New",
    westside: "Westside",
    downtown: "Downtown",
    midtown: "Midtown",
    north: "North",
    eastEnd: "East End",
    auto: "Auto",
    ourStoryTitle: "Our Story",
    ourStorySubtitle:
      "CityRent connects people with trusted local rental items across the city.",
    ourStoryBody:
      "Our platform helps owners list useful items and helps renters access what they need without buying everything outright.",
    careersTitle: "Careers",
    careersSubtitle: "Join the team building trusted citywide rentals.",
    careersBody:
      "We are looking for people who care about community, access, and better rental experiences.",
    howItWorksBrowseTitle: "Browse",
    howItWorksBrowseBody: "Search categories and find the item you need.",
    howItWorksBookTitle: "Book",
    howItWorksBookBody: "Select dates and confirm your rental.",
    howItWorksPickupTitle: "Pickup",
    howItWorksPickupBody: "Meet the owner and enjoy your rental.",
    privacyBody:
      "We use account and booking information to support rentals, messaging, notifications, and platform safety.",
    termsBody:
      "By using CityRent, users agree to follow rental, payment, cancellation, and item return policies.",
    contactEyebrow: "CONTACT",
    contactLead:
      "Reach out to CityRent support for account, listing, or booking help.",
    contactLocation: "Addis Ababa, Ethiopia",
    fullName: "Full Name",
    email: "Email",
    message: "Message",
    sendMessage: "Send Message",
    messageSent: "Message sent successfully.",
    browseRentals: "Browse Rentals",
    availableItems: "Available Items",
    availableItemsDescription:
      "Find vehicles, tools, electronics, cameras, furniture, and sports equipment for rent.",
    searchItemsPlaceholder: "Search items, categories, or locations",
    search: "Search",
    categoryNotFound: "Category Not Found",
    categoryNotFoundMessage: "The category you are looking for does not exist.",
    browseAllItems: "Browse All Items",
    browseAvailableRentalItems: "Browse available rental items.",
    itemNotFound: "Item not found",
    browseItems: "Browse Items",
    features: "Features",
    rentNow: "Rent Now",
  },
  om: {
    home: "Mana",
    categories: "Ramaddii",
    howItWorks: "Akkaataa Hojii",
    about: "Waa'ee Keenya",
    contact: "Nu Qunnami",
    contactUs: "Nu Qunnamaa",
    items: "Meeshaalee Barbaadi/Ilaali",
    registerLogin: "Galmaa'i / Seeni",
    loginRegister: "Seeni / Galmaa'i",
    dashboard: "Daashboordii",
    logout: "Ba'i",
    profile: "Profaayilii",
    messages: "Ergaawwan",
    language: "Afaan",
    footerTagline:
      "Sirna kiraa meeshaalee magaalaa - kiraa amanamaa magaalaa kee keessatti.",
    ourStory: "Seenaa Keenya",
    careers: "Carraa Hojii",
    privacyPolicy: "Imaammata Dhuunfaa",
    terms: "Waliigaltee",
    support: "Gargaarsa",
    legal: "Seera",
    openMenu: "Menuu bani",
    heroEyebrow: "DILAALAA AMANAMAA, KIRAA",
    heroCta: "Gara Tarreeffamaatti Deemi",
    heroDiscountOff: "HIR'INA",
    heroFeaturedAlt: "Meeshaa kiraa filatamaa",
    heroPrevious: "Islaayidii duraa",
    heroNext: "Islaayidii itti aanu",
    heroSlides: "Islaayidiiwwan jalqabaa",
    heroShowSlide: "Islaayidii agarsiisi",
    heroVehicleTitle: "Konkolaataa fi Geejjiba Naannoo Keessan Kireeffadhaa",
    heroVehicleSubtitle:
      "Kiraa konkolaataa abbootii naannoo amanamoo irraa ilaalaa.",
    heroElectronicsTitle: "Elektirooniksii Haala Kamiyyuu Kireeffadhaa",
    heroElectronicsSubtitle:
      "Laaptooppii, ispiikaraa, piroojektara, meeshaalee taphaa fi kanneen biroo argadhaa.",
    heroToolsTitle: "Meeshaalee Ogummaa Yeroo Barbaaddan",
    heroToolsSubtitle:
      "Baasiin bituu osoo hin jiraatin meeshaalee hojii fi meeshaalee gargaarsaa kireeffadhaa.",
    heroCameraTitle: "Kiraa Kaameraa Suuraa Hundumaaf",
    heroCameraSubtitle:
      "Taateewwan, qabiyyee fi hojii kalaqaaf kaameraa, leensii fi kiitii buufadhaa.",
    heroFurnitureTitle: "Kiraan Meeshaalee Manaa Salphaa Ta'e",
    heroFurnitureSubtitle:
      "Manaafi taateewwaniif kiraa meeshaalee manaa gatii madaalawaa.",
    heroSportsTitle: "Meeshaaleen Ispoortii Yeroo Ati Qophooftu Qophaa'oo",
    heroSportsSubtitle:
      "Biskileetii, meeshaalee goolfii, kaayaakii, meeshaalee ol-ba'uu fi alaa kireeffadhaa.",
    allItems: "Meeshaalee Hunda",
    usedItems: "Meeshaalee Fayyadamaman",
    newItems: "Meeshaalee Haaraa",
    category: "Ramaddii",
    allCategories: "Ramaddii Hunda",
    electronics: "Elektirooniksii",
    tools: "Meeshaalee Hojii",
    vehicles: "Konkolaataa",
    cameras: "Kaameraalee",
    sports: "Ispoortii",
    furniture: "Meeshaalee Manaa",
    maxPrice: "Gatii Ol'aanaa",
    maxPriceTitle: "Gatii ol'aanaa guyyaatti ETB",
    perDay: "guyyaa",
    searchRentals: "Kiraa Barbaadi",
    trustedRentalService: "TAJAAJILA KIRAA AMANAMAA",
    exploreAllItems: "Meeshaalee Hunda Ilaali",
    allStatus: "Haala Hunda",
    featured: "Filatamaa",
    rentalItem: "Meeshaa Kiraa",
    viewDetails: "BAL'INA ILAALI",
    compare: "Wal bira qabi",
    wishlist: "Fedhii",
    similar: "Walfakkaataa",
    suv: "SUV",
    camera: "Kaameraa",
    events: "Taateewwan",
    petrol: "Benzina",
    kit: "Kiitii",
    cordless: "Shiboo malee",
    likeNew: "Akka Haaraa",
    westside: "Gama Lixaa",
    downtown: "Giddugala Magaalaa",
    midtown: "Giddugala",
    north: "Kaabaa",
    eastEnd: "Gama Bahaa",
    auto: "Ofumaan",
    ourStoryTitle: "Seenaa Keenya",
    ourStorySubtitle:
      "CityRent namoota meeshaalee kiraa naannoo amanamoo waliin wal qunnamsiisa.",
    ourStoryBody:
      "Waltajjiin keenya abbootiin meeshaalee fayyadu tarreessuu fi kireeffattoonni osoo hin bitin wanta isaan barbaadan argachuu gargaara.",
    careersTitle: "Carraa Hojii",
    careersSubtitle: "Garee kiraa magaalaa amanamaa ijaaru waliin hojjedhaa.",
    careersBody:
      "Namoota hawaasa, argannaa fi muuxannoo kiraa fooyya'aa jaalatan barbaanna.",
    howItWorksBrowseTitle: "Ilaali",
    howItWorksBrowseBody: "Ramaddii barbaadiitii meeshaa si barbaachisu argadhu.",
    howItWorksBookTitle: "Buukii",
    howItWorksBookBody: "Guyyoota filadhuutii kiraa kee mirkaneessi.",
    howItWorksPickupTitle: "Fudhadhu",
    howItWorksPickupBody: "Abbaa meeshaa waliin wal argiitii kiraa kee fayyadami.",
    privacyBody:
      "Odeeffannoo herregaa fi buukii kiraa, ergaa, beeksisota fi nageenya waltajjii deeggaruuf fayyadamna.",
    termsBody:
      "CityRent fayyadamuun, fayyadamtoonni seera kiraa, kaffaltii, haqamuu fi deebisuu meeshaa hordofuuf walii galu.",
    contactEyebrow: "QUNNAMTII",
    contactLead:
      "Gargaarsa herregaa, tarreeffama ykn buukii argachuuf deeggarsa CityRent qunnamaa.",
    contactLocation: "Finfinnee, Itoophiyaa",
    fullName: "Maqaa Guutuu",
    email: "Imeelii",
    message: "Ergaa",
    sendMessage: "Ergaa Ergi",
    messageSent: "Ergaan milkaa'inaan ergame.",
    browseRentals: "Kiraa Ilaali",
    availableItems: "Meeshaalee Jiran",
    availableItemsDescription:
      "Konkolaataa, meeshaalee hojii, elektirooniksii, kaameraa, meeshaalee manaa fi meeshaalee ispoortii kiraaf argadhu.",
    searchItemsPlaceholder: "Meeshaalee, ramaddii ykn bakkeewwan barbaadi",
    search: "Barbaadi",
    categoryNotFound: "Ramaddiin Hin Argamne",
    categoryNotFoundMessage: "Ramaddiin ati barbaaddu hin jiru.",
    browseAllItems: "Meeshaalee Hunda Ilaali",
    browseAvailableRentalItems: "Meeshaalee kiraa jiran ilaali.",
    itemNotFound: "Meeshaan hin argamne",
    browseItems: "Meeshaalee Ilaali",
    features: "Amaloota",
    rentNow: "Amma Kireeffadhu",
  },
  am: {
    home: "መነሻ",
    categories: "ምድቦች",
    howItWorks: "እንዴት እንደሚሰራ",
    about: "ስለ እኛ",
    contact: "ያግኙን",
    contactUs: "ያግኙን",
    items: "እቃዎችን ፈልግ/አስስ",
    registerLogin: "ይመዝገቡ / ይግቡ",
    loginRegister: "ይግቡ / ይመዝገቡ",
    dashboard: "ዳሽቦርድ",
    logout: "ውጣ",
    profile: "መገለጫ",
    messages: "መልዕክቶች",
    language: "ቋንቋ",
    footerTagline:
      "Citywide Item Rental System - በከተማዎ ውስጥ የታመኑ ኪራዮች።",
    ourStory: "ታሪካችን",
    careers: "የስራ እድሎች",
    privacyPolicy: "የግላዊነት ፖሊሲ",
    terms: "ውሎች",
    support: "ድጋፍ",
    legal: "ሕጋዊ",
    openMenu: "ምናሌ ክፈት",
    heroEyebrow: "የታመነ አቅራቢ፣ ኪራይ",
    heroCta: "ወደ ዝርዝር ሂድ",
    heroDiscountOff: "ቅናሽ",
    heroFeaturedAlt: "ተመራጭ የኪራይ እቃ",
    heroPrevious: "ያለፈው ስላይድ",
    heroNext: "ቀጣይ ስላይድ",
    heroSlides: "የጀግና ስላይዶች",
    heroShowSlide: "ስላይድ አሳይ",
    heroVehicleTitle: "በአቅራቢያዎ መኪናዎችን እና ተሽከርካሪዎችን ይከራዩ",
    heroVehicleSubtitle: "ከታመኑ የአካባቢ ባለቤቶች የተሽከርካሪ ኪራዮችን ያስሱ።",
    heroElectronicsTitle: "ለማንኛውም አጋጣሚ ኤሌክትሮኒክስ ይከራዩ",
    heroElectronicsSubtitle:
      "ላፕቶፖች፣ ስፒከሮች፣ ፕሮጀክተሮች፣ የጨዋታ መሳሪያዎች እና ሌሎችንም ያግኙ።",
    heroToolsTitle: "በፍላጎት ጊዜ የሙያ መሳሪያዎች",
    heroToolsSubtitle: "የመግዛት ወጪ ሳይኖር መሳሪያዎችን እና እቃዎችን ይከራዩ።",
    heroCameraTitle: "ለማንኛውም ቀረጻ የካሜራ ኪራይ",
    heroCameraSubtitle:
      "ለክስተቶች፣ ይዘት እና ፈጠራ ስራ ካሜራዎች፣ ሌንሶች እና ኪቶችን ይያዙ።",
    heroFurnitureTitle: "የቤት እቃ ኪራይ ቀላል ሆኗል",
    heroFurnitureSubtitle: "ለቤቶች እና ክስተቶች ተመጣጣኝ የቤት እቃ ኪራይ።",
    heroSportsTitle: "የስፖርት እቃዎች ሲዘጋጁ ዝግጁ ናቸው",
    heroSportsSubtitle:
      "ብስክሌቶች፣ የጎልፍ ስብስቦች፣ ካያኮች፣ የመውጣት እቃዎች እና የውጭ መሳሪያዎችን ይከራዩ።",
    allItems: "ሁሉም እቃዎች",
    usedItems: "ያገለገሉ እቃዎች",
    newItems: "አዲስ እቃዎች",
    category: "ምድብ",
    allCategories: "ሁሉም ምድቦች",
    electronics: "ኤሌክትሮኒክስ",
    tools: "መሳሪያዎች",
    vehicles: "ተሽከርካሪዎች",
    cameras: "ካሜራዎች",
    sports: "ስፖርት",
    furniture: "የቤት እቃ",
    maxPrice: "ከፍተኛ ዋጋ",
    maxPriceTitle: "በቀን ከፍተኛ ዋጋ በETB",
    perDay: "ቀን",
    searchRentals: "ኪራዮችን ፈልግ",
    trustedRentalService: "የታመነ የኪራይ አገልግሎት",
    exploreAllItems: "ሁሉንም እቃዎች ያስሱ",
    allStatus: "ሁሉም ሁኔታ",
    featured: "ተመራጭ",
    rentalItem: "የኪራይ እቃ",
    viewDetails: "ዝርዝር ይመልከቱ",
    compare: "አወዳድር",
    wishlist: "የምኞት ዝርዝር",
    similar: "ተመሳሳይ",
    suv: "SUV",
    camera: "ካሜራ",
    events: "ክስተቶች",
    petrol: "ቤንዚን",
    kit: "ኪት",
    cordless: "ገመድ አልባ",
    likeNew: "እንደ አዲስ",
    westside: "ምዕራብ ክፍል",
    downtown: "መሃል ከተማ",
    midtown: "መካከለኛ ከተማ",
    north: "ሰሜን",
    eastEnd: "ምስራቅ ጫፍ",
    auto: "አውቶ",
    ourStoryTitle: "ታሪካችን",
    ourStorySubtitle:
      "CityRent ሰዎችን ከታመኑ የአካባቢ የኪራይ እቃዎች ጋር ያገናኛል።",
    ourStoryBody:
      "መድረካችን ባለቤቶች ጠቃሚ እቃዎችን እንዲዘረዝሩ እና ተከራዮች ሁሉንም ሳይገዙ የሚፈልጉትን እንዲያገኙ ይረዳል።",
    careersTitle: "የስራ እድሎች",
    careersSubtitle: "የታመኑ የከተማ ኪራዮችን ከሚገነባው ቡድን ጋር ይቀላቀሉ።",
    careersBody:
      "ለማህበረሰብ፣ ለተደራሽነት እና ለተሻለ የኪራይ ተሞክሮ የሚጨነቁ ሰዎችን እንፈልጋለን።",
    howItWorksBrowseTitle: "አስስ",
    howItWorksBrowseBody: "ምድቦችን ፈልገው የሚፈልጉትን እቃ ያግኙ።",
    howItWorksBookTitle: "ያስይዙ",
    howItWorksBookBody: "ቀኖችን ይምረጡ እና ኪራይዎን ያረጋግጡ።",
    howItWorksPickupTitle: "ይቀበሉ",
    howItWorksPickupBody: "ከባለቤቱ ጋር ይገናኙ እና ኪራይዎን ይጠቀሙ።",
    privacyBody:
      "ኪራዮችን፣ መልዕክቶችን፣ ማሳወቂያዎችን እና የመድረክ ደህንነትን ለመደገፍ የመለያ እና የቦታ ማስያዣ መረጃን እንጠቀማለን።",
    termsBody:
      "CityRentን በመጠቀም ተጠቃሚዎች የኪራይ፣ የክፍያ፣ የስረዛ እና የእቃ መመለሻ ፖሊሲዎችን ለመከተል ይስማማሉ።",
    contactEyebrow: "ያግኙን",
    contactLead:
      "ለመለያ፣ ለዝርዝር ወይም ለቦታ ማስያዣ እገዛ የCityRent ድጋፍን ያግኙ።",
    contactLocation: "አዲስ አበባ፣ ኢትዮጵያ",
    fullName: "ሙሉ ስም",
    email: "ኢሜይል",
    message: "መልዕክት",
    sendMessage: "መልዕክት ላክ",
    messageSent: "መልዕክቱ በተሳካ ሁኔታ ተልኳል።",
    browseRentals: "ኪራዮችን ያስሱ",
    availableItems: "ያሉ እቃዎች",
    availableItemsDescription:
      "ለኪራይ መኪናዎች፣ መሳሪያዎች፣ ኤሌክትሮኒክስ፣ ካሜራዎች፣ የቤት እቃዎች እና የስፖርት እቃዎችን ያግኙ።",
    searchItemsPlaceholder: "እቃዎችን፣ ምድቦችን ወይም ቦታዎችን ፈልግ",
    search: "ፈልግ",
    categoryNotFound: "ምድቡ አልተገኘም",
    categoryNotFoundMessage: "የሚፈልጉት ምድብ አይኖርም።",
    browseAllItems: "ሁሉንም እቃዎች ያስሱ",
    browseAvailableRentalItems: "ያሉ የኪራይ እቃዎችን ያስሱ።",
    itemNotFound: "እቃው አልተገኘም",
    browseItems: "እቃዎችን ያስሱ",
    features: "ባህሪያት",
    rentNow: "አሁን ይከራዩ",
  },
  so: {
    home: "Bogga Hore",
    categories: "Qaybaha",
    howItWorks: "Sida Ay U Shaqeyso",
    about: "Nagu Saabsan",
    contact: "Xiriir",
    contactUs: "Nala Soo Xiriir",
    items: "Raadi/Daawo Alaabta",
    registerLogin: "Isdiiwaangeli / Gal",
    loginRegister: "Gal / Isdiiwaangeli",
    dashboard: "Dashboard",
    logout: "Ka Bax",
    profile: "Profile",
    messages: "Fariimo",
    language: "Luqad",
    footerTagline:
      "Citywide Item Rental System - kirada la isku halleyn karo ee magaaladaada.",
    ourStory: "Sheekadeena",
    careers: "Shaqooyin",
    privacyPolicy: "Siyaasadda Asturnaanta",
    terms: "Shuruudaha",
    support: "Taageero",
    legal: "Sharci",
    openMenu: "Fur menu",
    heroEyebrow: "IIBIYE LA AAMINAYO, KIRO",
    heroCta: "Tag Liiska",
    heroDiscountOff: "DHIMIS",
    heroFeaturedAlt: "Alaab kiro oo la xushay",
    heroPrevious: "Slide-kii hore",
    heroNext: "Slide-ka xiga",
    heroSlides: "Slide-yada hero",
    heroShowSlide: "Muuji slide",
    heroVehicleTitle: "Ka Kireyso Baabuur iyo Gaadiid Agtaada",
    heroVehicleSubtitle:
      "Ka daawo kirada gaadiidka milkiilayaasha deegaanka ee la aamini karo.",
    heroElectronicsTitle: "Kireyso Elektaroonik Xaalad Kasta",
    heroElectronicsSubtitle:
      "Hel laptops, speakers, projectors, qalabka ciyaaraha, iyo wax ka badan.",
    heroToolsTitle: "Qalab Xirfadeed Markaad U Baahato",
    heroToolsSubtitle:
      "Kireyso qalab iyo agab adigoon qaadin kharashka lahaanshaha.",
    heroCameraTitle: "Kirada Kaamirooyinka Duubis Kasta",
    heroCameraSubtitle:
      "Qabsado kaamirooyin, lenses, iyo kits munaasabado, content, iyo shaqo hal-abuur leh.",
    heroFurnitureTitle: "Kirada Alaabta Guriga Way Fududaatay",
    heroFurnitureSubtitle:
      "Kiro alaab guri oo jaban oo loogu talagalay guryo iyo munaasabado.",
    heroSportsTitle: "Qalabka Ciyaaraha Waa Diyaar Markaad Diyaar Tahay",
    heroSportsSubtitle:
      "Kireyso baaskiillo, golf sets, kayaks, qalabka fuulista, iyo qalabka dibadda.",
    allItems: "Dhammaan Alaabta",
    usedItems: "Alaab La Isticmaalay",
    newItems: "Alaab Cusub",
    category: "Qayb",
    allCategories: "Dhammaan Qaybaha",
    electronics: "Elektaroonik",
    tools: "Qalab",
    vehicles: "Gaadiid",
    cameras: "Kaamirooyin",
    sports: "Ciyaaro",
    furniture: "Alaab Guri",
    maxPrice: "Qiimaha Ugu Badan",
    maxPriceTitle: "Qiimaha ugu badan maalintii ETB",
    perDay: "maalin",
    searchRentals: "Raadi Kiro",
    trustedRentalService: "ADEEG KIRO OO LA AAMINAYO",
    exploreAllItems: "Daawo Dhammaan Alaabta",
    allStatus: "Dhammaan Xaaladaha",
    featured: "La Xushay",
    rentalItem: "Alaab Kiro",
    viewDetails: "DAAWO FAAHFAAHIN",
    compare: "Isbarbar dhig",
    wishlist: "Liiska rabitaanka",
    similar: "La mid ah",
    suv: "SUV",
    camera: "Kaamiro",
    events: "Munaasabado",
    petrol: "Batrool",
    kit: "Kit",
    cordless: "Xadhig la'aan",
    likeNew: "Sida Cusub",
    westside: "Galbeed",
    downtown: "Bartamaha Magaalada",
    midtown: "Bartamaha",
    north: "Waqooyi",
    eastEnd: "Bari",
    auto: "Auto",
    ourStoryTitle: "Sheekadeena",
    ourStorySubtitle:
      "CityRent waxay dadka ku xirtaa alaab kiro oo deegaanka ah oo la isku halleyn karo.",
    ourStoryBody:
      "Madalkayagu wuxuu ka caawiyaa milkiilayaasha inay liis gareeyaan alaab waxtar leh, kiraystayaashana inay helaan waxa ay u baahan yihiin iyagoon iibsan.",
    careersTitle: "Shaqooyin",
    careersSubtitle: "Ku biir kooxda dhisaysa kiro magaalo oo la isku halleyn karo.",
    careersBody:
      "Waxaan raadineynaa dad daneeya bulshada, helitaanka, iyo khibrad kiro oo wanaagsan.",
    howItWorksBrowseTitle: "Daawo",
    howItWorksBrowseBody: "Raadi qaybaha oo hel alaabta aad u baahan tahay.",
    howItWorksBookTitle: "Qabso",
    howItWorksBookBody: "Dooro taariikhaha oo xaqiiji kiradaada.",
    howItWorksPickupTitle: "Qaado",
    howItWorksPickupBody: "La kulan milkiilaha oo ku raaxayso kiradaada.",
    privacyBody:
      "Waxaan u isticmaalnaa macluumaadka akoonka iyo booking-ka si aan u taageerno kirada, fariimaha, ogeysiisyada, iyo badbaadada madalka.",
    termsBody:
      "Marka la isticmaalo CityRent, isticmaalayaashu waxay oggolaanayaan inay raacaan siyaasadaha kirada, lacag bixinta, baajinta, iyo soo celinta alaabta.",
    contactEyebrow: "XIRIIR",
    contactLead:
      "La xiriir taageerada CityRent si aad uga hesho caawimaad akoon, liis, ama booking.",
    contactLocation: "Addis Ababa, Ethiopia",
    fullName: "Magaca Buuxa",
    email: "Email",
    message: "Fariin",
    sendMessage: "Dir Fariin",
    messageSent: "Fariinta si guul leh ayaa loo diray.",
    browseRentals: "Daawo Kirooyinka",
    availableItems: "Alaabta La Heli Karo",
    availableItemsDescription:
      "Hel gaadiid, qalab, elektaroonik, kaamirooyin, alaab guri, iyo qalab ciyaaro oo kiro ah.",
    searchItemsPlaceholder: "Raadi alaab, qaybo, ama goobaha",
    search: "Raadi",
    categoryNotFound: "Qayb Lama Helin",
    categoryNotFoundMessage: "Qaybta aad raadinayso ma jirto.",
    browseAllItems: "Daawo Dhammaan Alaabta",
    browseAvailableRentalItems: "Daawo alaabta kirada ee la heli karo.",
    itemNotFound: "Alaabta lama helin",
    browseItems: "Daawo Alaabta",
    features: "Astaamaha",
    rentNow: "Hadda Kireyso",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem("language") || "en",
  );

  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem("language", language);
  }, [language]);

  const t = useCallback((key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t,
      translations,
    }),
    [language, t],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }

  return context;
}
