/* eslint-disable react-refresh/only-export-components */
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

const LanguageContext = createContext(null);

const translations = {
  en: {
    // --- Nav & General ---
    home: "Home",
    categories: "Categories",
    howItWorks: "How It Works",
    about: "About",
    contact: "Contact",
    contactUs: "Contact Us",
    items: "Search/Browse Items",
    registerLogin: "Register / Login",
    loginRegister: "Login / Register",
    dashboard: "Dashboard",
    logout: "Logout",
    profile: "Profile",
    messages: "Messages",
    language: "Language",
    memberSince: "Member since",
    myProfile: "My Profile",
    payment: "Payment",
    performance: "Performance",
    feedback: "Feedback",
    notifications: "Notifications",
    reviewHistory: "Review History",
    privacySecurity: "Privacy & Security",
    settings: "Settings",

    // --- Footer ---
    footerTagline: "The premium rental marketplace connecting communities across Jigjiga, Dire Dawa, and Harar.",
    ourStory: "Our Story",
    careers: "Careers",
    privacyPolicy: "Privacy Policy",
    terms: "Terms",
    support: "Support",
    legal: "Legal",

    // --- Hero ---
    openMenu: "Open menu",
    heroEyebrow: "TRUSTED RENTAL MARKETPLACE",
    heroCta: "Browse Listings",
    heroDiscountOff: "OFF",
    heroFeaturedAlt: "Featured rental item",
    heroPrevious: "Previous slide",
    heroNext: "Next slide",
    heroSlides: "Hero slides",
    heroShowSlide: "Show slide",
    heroVehicleTitle: "Rent Cars & Vehicles Near You",
    heroVehicleSubtitle: "Browse trusted vehicle rentals from local owners.",
    heroElectronicsTitle: "Rent Electronics For Any Occasion",
    heroElectronicsSubtitle: "Find laptops, speakers, projectors, gaming devices, and more.",
    heroToolsTitle: "Professional Tools On Demand",
    heroToolsSubtitle: "Rent tools and equipment without the cost of ownership.",
    heroCameraTitle: "Camera Rentals For Every Shoot",
    heroCameraSubtitle: "Book cameras, lenses, and kits for events, content, and creative work.",
    heroFurnitureTitle: "Furniture Rentals Made Easy",
    heroFurnitureSubtitle: "Affordable furniture rentals for homes and events.",
    heroSportsTitle: "Sports Gear Ready When You Are",
    heroSportsSubtitle: "Rent bikes, golf sets, kayaks, climbing gear, and outdoor equipment.",

    // --- Search & Categories ---
    allItems: "All Items",
    usedItems: "Used Items",
    newItems: "New Items",
    category: "Category",
    allCategories: "All Categories",
    electronics: "Electronics",
    tools: "Tools",
    vehicles: "Vehicles",
    cameras: "Cameras",
    sports: "Sports",
    furniture: "Furniture",
    maxPrice: "Max Price",
    maxPriceTitle: "Max price per day in ETB",
    perDay: "day",
    searchRentals: "Search Rentals",
    trustedRentalService: "TRUSTED RENTAL SERVICE",
    exploreAllItems: "Explore All Items",
    allStatus: "All Status",
    featured: "Featured",
    rentalItem: "Rental Item",
    viewDetails: "View Details",
    compare: "Compare",
    wishlist: "Wishlist",
    similar: "Similar",
    suv: "SUV",
    camera: "Camera",
    events: "Events",
    petrol: "Petrol",
    kit: "Kit",
    cordless: "Cordless",
    likeNew: "Like New",
    westside: "Westside",
    downtown: "Downtown",
    midtown: "Midtown",
    north: "North",
    eastEnd: "East End",
    auto: "Auto",
    anyCondition: "Any Condition",
    used: "Used",
    location: "Location",
    allCities: "All Cities",
    findRentals: "Find Rentals",
    sefar: "Neighbourhood",
    allSefar: "All Neighbourhoods",
    neighbourhood: "Neighbourhood",

    // --- About / How It Works ---
    ourStoryTitle: "Our Story",
    ourStorySubtitle: "EasternCity connects people with trusted local rental items across the city.",
    ourStoryBody: "Our platform helps owners list useful items and helps renters access what they need without buying everything outright.",
    careersTitle: "Careers",
    careersSubtitle: "Join the team building trusted citywide rentals.",
    careersBody: "We are looking for people who care about community, access, and better rental experiences.",
    howItWorksBrowseTitle: "Browse",
    howItWorksBrowseBody: "Search categories and find the item you need.",
    howItWorksBookTitle: "Book",
    howItWorksBookBody: "Select dates and confirm your rental.",
    howItWorksPickupTitle: "Pickup",
    howItWorksPickupBody: "Meet the owner and enjoy your rental.",

    // --- About Page ---
    aboutEyebrow: "ABOUT EASTERNCITIES",
    aboutHeroTitle: "Connecting Communities Through Trust",
    aboutHeroDesc: "EasternCities connects people who own useful items with people who need them - safely, affordably, and instantly across Eastern Ethiopia.",
    aboutMissionTitle: "Our Mission",
    aboutMissionBody: "To make renting as easy and trusted as borrowing from a friend. We believe every item sitting unused in your home could be earning money — and every renter deserves access to quality items without buying them outright.",
    aboutWhoWeAreTitle: "Who We Are",
    aboutWhoWeAreBody: "EasternCities was founded in Jigjiga with a simple idea: the sharing economy should work for Eastern Ethiopia. We're a team of local technologists, community leaders, and entrepreneurs building trust-based infrastructure for peer-to-peer rental.",
    aboutWhyChooseUs: "WHY CHOOSE US",
    aboutBuiltOnValues: "Built on Values That Matter",
    aboutTrustTitle: "Trust & Safety",
    aboutTrustBody: "Every listing is verified. Every renter is ID-checked. Every transaction is escrow-protected.",
    aboutCommunityTitle: "Community First",
    aboutCommunityBody: "We connect neighbours. Real people with real items, building local economic opportunity.",
    aboutSpeedTitle: "Speed & Convenience",
    aboutSpeedBody: "Search, book, and collect in minutes. No paperwork, no delays.",
    aboutMultilingualTitle: "Multilingual",
    aboutMultilingualBody: "Fully accessible in English, Amharic, Somali, and Afaan Oromo.",
    aboutCoverageEyebrow: "OUR COVERAGE",
    aboutCitiesTitle: "Cities We Serve",
    aboutJigjigaDesc: "Capital of Somali Region. Our largest market.",
    aboutDireDawaDesc: "Industrial hub with high demand for tool & equipment rentals.",
    aboutHararDesc: "Historic walled city. Perfect for event and furniture rentals.",
    aboutCtaTitle: "Ready to rent smarter?",
    aboutCtaBody: "Join thousands of verified members renting across Eastern Ethiopia today.",
    aboutCtaGetStarted: "Get Started Free",
    aboutCtaBrowse: "Browse Listings",

    // --- Legal / Contact ---
    privacyBody: "We use account and booking information to support rentals, messaging, notifications, and platform safety.",
    termsBody: "By using EasternCity, users agree to follow rental, payment, cancellation, and item return policies.",
    contactEyebrow: "CONTACT",
    contactLead: "Reach out to EasternCity support for account, listing, or booking help.",
    contactLocation: "Jigjiga / Dire Dawa / Harar, Ethiopia",
    fullName: "Full Name",
    email: "Email",
    message: "Message",
    sendMessage: "Send Message",
    messageSent: "Message sent successfully.",

    // --- Listings / Item Details ---
    browseRentals: "Browse Rentals",
    availableItems: "Available Items",
    availableItemsDescription: "Find vehicles, tools, electronics, cameras, furniture, and sports equipment for rent.",
    searchItemsPlaceholder: "Search items, categories, or locations",
    search: "Search",
    categoryNotFound: "Category Not Found",
    categoryNotFoundMessage: "The category you are looking for does not exist.",
    browseAllItems: "Browse All Items",
    browseAvailableRentalItems: "Browse available rental items.",
    itemNotFound: "Item not found",
    browseItems: "Browse Items",
    features: "Features",
    rentNow: "Rent Now",
    description: "Description",
    rentalConditions: "Rental Conditions",
    ownerInfo: "Owner Info",
    reviews: "Reviews",
    similarListings: "Similar Listings",
    requestToBook: "Request to Book",
    contactOwner: "Contact Owner",
    rentalGuarantee: "Rental Guarantee",
    paymentMethods: "Payment Methods",
    securityDeposit: "Security Deposit",
    refundableAfterReturn: "Refundable after return",
    requiredVerification: "Required Verification",
    nationalId: "National ID (Kebele ID)",
    rentalConditionsNote: "Item must be returned in original condition.",
    available: "Available",
    perDayLabel: "/day",

    // --- Booking Flow ---
    completeYourBooking: "Complete Your Booking",
    startDate: "Start Date",
    endDate: "End Date",
    priceBreakdown: "Price Breakdown",
    serviceFee: "Service Fee (5%)",
    total: "Total",
    continue: "Continue",
    rentalAgreement: "Rental Agreement",
    agreeAndContinue: "Agree & Continue",
    back: "Back",
    uploadPaymentReceipt: "Upload Payment Receipt",
    submitBooking: "Submit Booking",
    bookingSubmitted: "Booking submitted! Awaiting verification.",
    paymentRequired: "A payment screenshot is required to complete booking.",
    selectDates: "Please select rental dates.",
    endAfterStart: "End date must be after start date.",
    acceptRules: "You must accept the rental rules.",
    transferAmount: "Please transfer the amount and upload the receipt screenshot.",
    cbe: "CBE",
    ebirr: "eBirr",
    telebirr: "Telebirr",
    accountNumber: "Account Number",

    // --- Dashboard ---
    myListings: "My Listings",
    myBookings: "My Bookings",
    savedItems: "Saved Items",
    addNewListing: "Add New Listing",
    editListing: "Edit Listing",
    deleteListing: "Delete Listing",
    bookingHistory: "Booking History",
    activeRentals: "Active Rentals",
    pendingApproval: "Pending Approval",
    approved: "Approved",
    rejected: "Rejected",
    awaitingVerification: "Awaiting Verification",
    completed: "Completed",
    cancelled: "Cancelled",
    totalEarnings: "Total Earnings",
    totalBookings: "Total Bookings",
    totalListings: "Total Listings",
    averageRating: "Average Rating",
    recentActivity: "Recent Activity",

    // --- Admin ---
    adminPanel: "Admin Panel",
    superAdminPanel: "Super Admin Panel",
    manageUsers: "Manage Users",
    manageListings: "Manage Listings",
    manageBookings: "Manage Bookings",
    reports: "Reports",
    approveItem: "Approve",
    rejectItem: "Reject",
    suspendUser: "Suspend User",
    activateUser: "Activate User",
    userManagement: "User Management",
    statistics: "Statistics",
    systemSettings: "System Settings",
    platformOverview: "Platform Overview",
  },

  af: {
    // --- Nav & General ---
    home: "Mana",
    categories: "Ramaddii",
    howItWorks: "Akkaataa Hojii",
    about: "Waa'ee Keenya",
    contact: "Nu Qunnami",
    contactUs: "Nu Qunnamaa",
    items: "Meeshaalee Barbaadi/Ilaali",
    registerLogin: "Galmaa'i / Seeni",
    loginRegister: "Seeni / Galmaa'i",
    dashboard: "Daashboordii",
    logout: "Ba'i",
    profile: "Profaayilii",
    messages: "Ergaawwan",
    language: "Afaan",
    memberSince: "Miseensa kan ta'e",
    myProfile: "Profaayilii Koo",
    payment: "Kaffaltii",
    performance: "Raawwii",
    feedback: "Deebii",
    notifications: "Beeksisota",
    reviewHistory: "Seenaa Madaallii",
    privacySecurity: "Dhuunfaa & Nageenyaa",
    settings: "Qindaa'ina",

    // --- Footer ---
    footerTagline: "Sirna kiraa meeshaalee magaalaa - kiraa amanamaa magaalaa kee keessatti.",
    ourStory: "Seenaa Keenya",
    careers: "Carraa Hojii",
    privacyPolicy: "Imaammata Dhuunfaa",
    terms: "Waliigaltee",
    support: "Gargaarsa",
    legal: "Seera",

    // --- Hero ---
    openMenu: "Menuu bani",
    heroEyebrow: "GABATEE KIRAA AMANAMAA",
    heroCta: "Tarreeffamaatti Seeni",
    heroDiscountOff: "HIR'INA",
    heroFeaturedAlt: "Meeshaa kiraa filatamaa",
    heroPrevious: "Islaayidii duraa",
    heroNext: "Islaayidii itti aanu",
    heroSlides: "Islaayidiiwwan jalqabaa",
    heroShowSlide: "Islaayidii agarsiisi",
    heroVehicleTitle: "Konkolaataa fi Geejjiba Naannoo Keessan Kireeffadhaa",
    heroVehicleSubtitle: "Kiraa konkolaataa abbootii naannoo amanamoo irraa ilaalaa.",
    heroElectronicsTitle: "Elektirooniksii Haala Kamiyyuu Kireeffadhaa",
    heroElectronicsSubtitle: "Laaptooppii, ispiikaraa, piroojektara, meeshaalee taphaa fi kanneen biroo argadhaa.",
    heroToolsTitle: "Meeshaalee Ogummaa Yeroo Barbaaddan",
    heroToolsSubtitle: "Baasiin bituu osoo hin jiraatin meeshaalee hojii fi meeshaalee gargaarsaa kireeffadhaa.",
    heroCameraTitle: "Kiraa Kaameraa Suuraa Hundumaaf",
    heroCameraSubtitle: "Taateewwan, qabiyyee fi hojii kalaqaaf kaameraa, leensii fi kiitii buufadhaa.",
    heroFurnitureTitle: "Kiraan Meeshaalee Manaa Salphaa Ta'e",
    heroFurnitureSubtitle: "Manaafi taateewwaniif kiraa meeshaalee manaa gatii madaalawaa.",
    heroSportsTitle: "Meeshaaleen Ispoortii Yeroo Ati Qophooftu Qophaa'oo",
    heroSportsSubtitle: "Biskileetii, meeshaalee goolfii, kaayaakii, meeshaalee ol-ba'uu fi alaa kireeffadhaa.",

    // --- Search & Categories ---
    allItems: "Meeshaalee Hunda",
    usedItems: "Meeshaalee Fayyadamaman",
    newItems: "Meeshaalee Haaraa",
    category: "Ramaddii",
    allCategories: "Ramaddii Hunda",
    electronics: "Elektirooniksii",
    tools: "Meeshaalee Hojii",
    vehicles: "Konkolaataa",
    cameras: "Kaameraalee",
    sports: "Ispoortii",
    furniture: "Meeshaalee Manaa",
    maxPrice: "Gatii Ol'aanaa",
    maxPriceTitle: "Gatii ol'aanaa guyyaatti ETB",
    perDay: "guyyaa",
    searchRentals: "Kiraa Barbaadi",
    trustedRentalService: "TAJAAJILA KIRAA AMANAMAA",
    exploreAllItems: "Meeshaalee Hunda Ilaali",
    allStatus: "Haala Hunda",
    featured: "Filatamaa",
    rentalItem: "Meeshaa Kiraa",
    viewDetails: "Bal'ina Ilaali",
    compare: "Wal bira qabi",
    wishlist: "Fedhii",
    similar: "Walfakkaataa",
    suv: "SUV",
    camera: "Kaameraa",
    events: "Taateewwan",
    petrol: "Benzina",
    kit: "Kiitii",
    cordless: "Shiboo malee",
    likeNew: "Akka Haaraa",
    westside: "Gama Lixaa",
    downtown: "Giddugala Magaalaa",
    midtown: "Giddugala",
    north: "Kaabaa",
    eastEnd: "Gama Bahaa",
    auto: "Ofumaan",
    anyCondition: "Haala Kamiyyuu",
    used: "Fayyadamame",
    location: "Bakka",
    allCities: "Magaalota Hunda",
    findRentals: "Kiraa Barbaadi",
    sefar: "Naannoo",
    allSefar: "Naannoo Hunda",
    neighbourhood: "Naannoo",

    // --- About / How It Works ---
    ourStoryTitle: "Seenaa Keenya",
    ourStorySubtitle: "EasternCity namoota meeshaalee kiraa naannoo amanamoo waliin wal qunnamsiisa.",
    ourStoryBody: "Waltajjiin keenya abbootiin meeshaalee fayyadu tarreessuu fi kireeffattoonni osoo hin bitin wanta isaan barbaadan argachuu gargaara.",
    careersTitle: "Carraa Hojii",
    careersSubtitle: "Garee kiraa magaalaa amanamaa ijaaru waliin hojjedhaa.",
    careersBody: "Namoota hawaasa, argannaa fi muuxannoo kiraa fooyya'aa jaalatan barbaanna.",
    howItWorksBrowseTitle: "Ilaali",
    howItWorksBrowseBody: "Ramaddii barbaadiitii meeshaa si barbaachisu argadhu.",
    howItWorksBookTitle: "Buukii",
    howItWorksBookBody: "Guyyoota filadhuutii kiraa kee mirkaneessi.",
    howItWorksPickupTitle: "Fudhadhu",
    howItWorksPickupBody: "Abbaa meeshaa waliin wal argiitii kiraa kee fayyadami.",

    // --- About Page ---
    aboutEyebrow: "WAAEE EASTERNCITIES",
    aboutHeroTitle: "Hawaasota Amanamuummaan Walqunnamsiisuu",
    aboutHeroDesc: "EasternCities namoota meeshaalee gargaaramoo qaban fi kan isaan barbaadan - nagaan, gatii madaalawaadhaan, yeroo hundaa Itoophiyaa Bahaa keessatti walqunnamsiisa.",
    aboutMissionTitle: "Kaayyoo Keenya",
    aboutMissionBody: "Kiraa hirmaannaa amansiisaa fi salphaa akka michuu irraa liqeeffachuutti taasisuu. Meeshaaleen mana keessan keessa taa'an galii argachuu danda'u — kireeffattoonnis meeshaa qulqulluu osoo hin bitiin argachuu qabu.",
    aboutWhoWeAreTitle: "Eenyuu Feeti",
    aboutWhoWeAreBody: "EasternCities Jigjiga keessatti yaad-rimee salphaadhaan hundaa'e: diinagdeen qooduu Itoophiyaa Bahaa keessatti hojjechuu qaba. Tekinoolojistootaa fi namoonni hawaasaa fi hojjetootni damee kiraa namoota gidduutti amansiisaa ijaaraa jirra.",
    aboutWhyChooseUs: "MAALIIF NU FILATTA",
    aboutBuiltOnValues: "Gatii Barbaachisoo Irra Ijaarame",
    aboutTrustTitle: "Amanamuummaa fi Nageenyaa",
    aboutTrustBody: "Tarreeffamni hundumtuu mirkana'eera. Kireeftamtoonni hundumtuu eenyummaadhaan mirkanaa'u. Hariiroon hundumtuu escrow-iin eegama.",
    aboutCommunityTitle: "Hawaasni Dursa",
    aboutCommunityBody: "Ollootaa walqunnamsiisna. Namoota dhugaa meeshaalee dhugaa qaban waliin, carraa diinagdee naannoo ijaaraa.",
    aboutSpeedTitle: "Ariifannaa fi Mijatummaa",
    aboutSpeedBody: "Barbaadi, buukii godhi, fudhanna. Waraqaa hin barbaachisu, hin tursiisu.",
    aboutMultilingualTitle: "Afaanota Hedduudhaan",
    aboutMultilingualBody: "Afaan Ingilizii, Amaaraa, Soomaali, fi Afaan Oromoottiin ni argama.",
    aboutCoverageEyebrow: "HAGUUGGINNI KEENYA",
    aboutCitiesTitle: "Magaalota Tajaajillu",
    aboutJigjigaDesc: "Mootummaa Naannoo Somaalee. Gabata keenya guddaa.",
    aboutDireDawaDesc: "Giddugala industirii meeshaalee hojii fi qophinaalee kiraa barbaadu.",
    aboutHararDesc: "Magaala duudhaa eeguumsa gamoo qabu. Taateewwan fi kiraa meeshaalee manaadhaf mijataa.",
    aboutCtaTitle: "Kiraa Qalbii-qabsiisuun Qopha'aa?",
    aboutCtaBody: "Miseensota mirkanaa'oo kuma hedduudhaan waliin Itoophiyaa Bahaa keessatti kiraa godhi.",
    aboutCtaGetStarted: "Eegaluu Bilisa",
    aboutCtaBrowse: "Tarreeffamoota Ilaali",

    // --- Legal / Contact ---
    privacyBody: "Odeeffannoo herregaa fi buukii kiraa, ergaa, beeksisota fi nageenya waltajjii deeggaruuf fayyadamna.",
    termsBody: "EasternCity fayyadamuun, fayyadamtoonni seera kiraa, kaffaltii, haqamuu fi deebisuu meeshaa hordofuuf walii galu.",
    contactEyebrow: "QUNNAMTII",
    contactLead: "Gargaarsa herregaa, tarreeffama ykn buukii argachuuf deeggarsa EasternCity qunnamaa.",
    contactLocation: "Jigjiga / Dire Dawa / Harar, Itoophiyaa",
    fullName: "Maqaa Guutuu",
    email: "Imeelii",
    message: "Ergaa",
    sendMessage: "Ergaa Ergi",
    messageSent: "Ergaan milkaa'inaan ergame.",

    // --- Listings / Item Details ---
    browseRentals: "Kiraa Ilaali",
    availableItems: "Meeshaalee Jiran",
    availableItemsDescription: "Konkolaataa, meeshaalee hojii, elektirooniksii, kaameraa, meeshaalee manaa fi meeshaalee ispoortii kiraaf argadhu.",
    searchItemsPlaceholder: "Meeshaalee, ramaddii ykn bakkeewwan barbaadi",
    search: "Barbaadi",
    categoryNotFound: "Ramaddiin Hin Argamne",
    categoryNotFoundMessage: "Ramaddiin ati barbaaddu hin jiru.",
    browseAllItems: "Meeshaalee Hunda Ilaali",
    browseAvailableRentalItems: "Meeshaalee kiraa jiran ilaali.",
    itemNotFound: "Meeshaan hin argamne",
    browseItems: "Meeshaalee Ilaali",
    features: "Amaloota",
    rentNow: "Amma Kireeffadhu",
    description: "Ibsa",
    rentalConditions: "Haala Kiraa",
    ownerInfo: "Odeeffannoo Abbaa",
    reviews: "Madaallii",
    similarListings: "Tarreeffama Walfakkaataa",
    requestToBook: "Buukii Gaafadhu",
    contactOwner: "Abbaa Qunnami",
    rentalGuarantee: "Mirkaneessa Kiraa",
    paymentMethods: "Mala Kaffaltii",
    securityDeposit: "Kaffaltii Nageenyaa",
    refundableAfterReturn: "Deebifama deebisuu booda",
    requiredVerification: "Mirkaneessa Barbaachisaa",
    nationalId: "Eenyummaa Biyyalessaa (Kebele ID)",
    rentalConditionsNote: "Meeshaan haala jalqabaatiin deebifamuu qaba.",
    available: "Argama",
    perDayLabel: "/guyyaa",

    // --- Booking Flow ---
    completeYourBooking: "Buukii Kee Xumuuri",
    startDate: "Guyyaa Jalqabaa",
    endDate: "Guyyaa Xumuraa",
    priceBreakdown: "Ibsa Gatii",
    serviceFee: "Kaffaltii Tajaajilaa (5%)",
    total: "Walitti ida'ama",
    continue: "Itti fufi",
    rentalAgreement: "Waliigaltee Kiraa",
    agreeAndContinue: "Walii Gali & Itti Fufi",
    back: "Duubatti",
    uploadPaymentReceipt: "Ragaa Kaffaltii Fe'i",
    submitBooking: "Buukii Ergi",
    bookingSubmitted: "Buukiin ergame! Mirkaneessa eegaa.",
    paymentRequired: "Suuraa kaffaltii buukii xumuruuf barbaachisaa.",
    selectDates: "Maaloo guyyoota kiraa filadhu.",
    endAfterStart: "Guyyaan xumuraa guyyaa jalqabaa booda ta'uu qaba.",
    acceptRules: "Seerota kiraa fudhachuu qabda.",
    transferAmount: "Maaloo qarshii dabarsi fi suuraa mirkaneessa fe'i.",
    cbe: "CBE",
    ebirr: "eBirr",
    telebirr: "Telebirr",
    accountNumber: "Lakkoofsa Herregaa",

    // --- Dashboard ---
    myListings: "Tarreeffama Koo",
    myBookings: "Buukii Koo",
    savedItems: "Meeshaalee Kuufaman",
    addNewListing: "Tarreeffama Haaraa Ida'i",
    editListing: "Tarreeffama Gulaali",
    deleteListing: "Tarreeffama Haqii",
    bookingHistory: "Seenaa Buukii",
    activeRentals: "Kiraa Hojii Irra Jiran",
    pendingApproval: "Mirkaneessa Eegaa",
    approved: "Mirkanaa'e",
    rejected: "Dhorkaame",
    awaitingVerification: "Mirkaneessa Eegaa",
    completed: "Xumurame",
    cancelled: "Haqame",
    totalEarnings: "Galii Waliigalaa",
    totalBookings: "Buukii Waliigalaa",
    totalListings: "Tarreeffama Waliigalaa",
    averageRating: "Madaallii Jiddu Galeessaa",
    recentActivity: "Hojii Dhiyeenyaa",

    // --- Admin ---
    adminPanel: "Mana Bulchiinsaa",
    superAdminPanel: "Mana Bulchiinsaa Ol'aanaa",
    manageUsers: "Fayyadamtoota Bulchi",
    manageListings: "Tarreeffamoota Bulchi",
    manageBookings: "Buukii Bulchi",
    reports: "Gabaasa",
    approveItem: "Hayyami",
    rejectItem: "Dhowwi",
    suspendUser: "Fayyadamaa Dhaabi",
    activateUser: "Fayyadamaa Hoji Jalqabsiisi",
    userManagement: "Bulchiinsa Fayyadamaa",
    statistics: "Tilmaama",
    systemSettings: "Qindaa'ina Sirna",
    platformOverview: "Waliigala Waltajjii",
  },

  am: {
    // --- Nav & General ---
    home: "መነሻ",
    categories: "ምድቦች",
    howItWorks: "እንዴት እንደሚሰራ",
    about: "ስለ እኛ",
    contact: "ያግኙን",
    contactUs: "ያግኙን",
    items: "እቃዎችን ፈልግ/አስስ",
    registerLogin: "ይመዝገቡ / ይግቡ",
    loginRegister: "ይግቡ / ይመዝገቡ",
    dashboard: "ዳሽቦርድ",
    logout: "ውጣ",
    profile: "መገለጫ",
    messages: "መልዕክቶች",
    language: "ቋንቋ",
    memberSince: "አባል ከ",
    myProfile: "የእኔ መገለጫ",
    payment: "ክፍያ",
    performance: "አፈጻጸም",
    feedback: "አስተያየት",
    notifications: "ማሳወቂያዎች",
    reviewHistory: "የግምገማ ታሪክ",
    privacySecurity: "ግላዊነት እና ደህንነት",
    settings: "ቅንብሮች",

    // --- Footer ---
    footerTagline: "ፕሪሚየም የኪራይ ገበያ ጂጂጋ፣ ድሬዳዋ እና ሀረርን ያገናኛል።",
    ourStory: "ታሪካችን",
    careers: "የስራ እድሎች",
    privacyPolicy: "የግላዊነት ፖሊሲ",
    terms: "ውሎች",
    support: "ድጋፍ",
    legal: "ሕጋዊ",

    // --- Hero ---
    openMenu: "ምናሌ ክፈት",
    heroEyebrow: "የታመነ የኪራይ ገበያ",
    heroCta: "ዝርዝሮችን አስስ",
    heroDiscountOff: "ቅናሽ",
    heroFeaturedAlt: "ተመራጭ የኪራይ እቃ",
    heroPrevious: "ያለፈው ስላይድ",
    heroNext: "ቀጣይ ስላይድ",
    heroSlides: "የጀግና ስላይዶች",
    heroShowSlide: "ስላይድ አሳይ",
    heroVehicleTitle: "በአቅራቢያዎ መኪናዎችን እና ተሽከርካሪዎችን ይከራዩ",
    heroVehicleSubtitle: "ከታመኑ የአካባቢ ባለቤቶች የተሽከርካሪ ኪራዮችን ያስሱ።",
    heroElectronicsTitle: "ለማንኛውም አጋጣሚ ኤሌክትሮኒክስ ይከራዩ",
    heroElectronicsSubtitle: "ላፕቶፖች፣ ስፒከሮች፣ ፕሮጀክተሮች፣ የጨዋታ መሳሪያዎች እና ሌሎችንም ያግኙ።",
    heroToolsTitle: "በፍላጎት ጊዜ የሙያ መሳሪያዎች",
    heroToolsSubtitle: "የመግዛት ወጪ ሳይኖር መሳሪያዎችን እና እቃዎችን ይከራዩ።",
    heroCameraTitle: "ለማንኛውም ቀረጻ የካሜራ ኪራይ",
    heroCameraSubtitle: "ለክስተቶች፣ ይዘት እና ፈጠራ ስራ ካሜራዎች፣ ሌንሶች እና ኪቶችን ይያዙ።",
    heroFurnitureTitle: "የቤት እቃ ኪራይ ቀላል ሆኗል",
    heroFurnitureSubtitle: "ለቤቶች እና ክስተቶች ተመጣጣኝ የቤት እቃ ኪራይ።",
    heroSportsTitle: "የስፖርት እቃዎች ሲዘጋጁ ዝግጁ ናቸው",
    heroSportsSubtitle: "ብስክሌቶች፣ የጎልፍ ስብስቦች፣ ካያኮች፣ የመውጣት እቃዎች እና የውጭ መሳሪያዎችን ይከራዩ።",

    // --- Search & Categories ---
    allItems: "ሁሉም እቃዎች",
    usedItems: "ያገለገሉ እቃዎች",
    newItems: "አዲስ እቃዎች",
    category: "ምድብ",
    allCategories: "ሁሉም ምድቦች",
    electronics: "ኤሌክትሮኒክስ",
    tools: "መሳሪያዎች",
    vehicles: "ተሽከርካሪዎች",
    cameras: "ካሜራዎች",
    sports: "ስፖርት",
    furniture: "የቤት እቃ",
    maxPrice: "ከፍተኛ ዋጋ",
    maxPriceTitle: "በቀን ከፍተኛ ዋጋ በETB",
    perDay: "ቀን",
    searchRentals: "ኪራዮችን ፈልግ",
    trustedRentalService: "የታመነ የኪራይ አገልግሎት",
    exploreAllItems: "ሁሉንም እቃዎች ያስሱ",
    allStatus: "ሁሉም ሁኔታ",
    featured: "ተመራጭ",
    rentalItem: "የኪራይ እቃ",
    viewDetails: "ዝርዝር ይመልከቱ",
    compare: "አወዳድር",
    wishlist: "የምኞት ዝርዝር",
    similar: "ተመሳሳይ",
    suv: "SUV",
    camera: "ካሜራ",
    events: "ክስተቶች",
    petrol: "ቤንዚን",
    kit: "ኪት",
    cordless: "ገመድ አልባ",
    likeNew: "እንደ አዲስ",
    westside: "ምዕራብ ክፍል",
    downtown: "መሃል ከተማ",
    midtown: "መካከለኛ ከተማ",
    north: "ሰሜን",
    eastEnd: "ምስራቅ ጫፍ",
    auto: "አውቶ",
    anyCondition: "ማንኛውም ሁኔታ",
    used: "ያገለገለ",
    location: "ቦታ",
    allCities: "ሁሉም ከተሞች",
    findRentals: "ኪራዮችን ፈልግ",
    sefar: "ሰፈር",
    allSefar: "ሁሉም ሰፈሮች",
    neighbourhood: "ሰፈር",

    // --- About / How It Works ---
    ourStoryTitle: "ታሪካችን",
    ourStorySubtitle: "EasternCity ሰዎችን ከታመኑ የአካባቢ የኪራይ እቃዎች ጋር ያገናኛል።",
    ourStoryBody: "መድረካችን ባለቤቶች ጠቃሚ እቃዎችን እንዲዘረዝሩ እና ተከራዮች ሁሉንም ሳይገዙ የሚፈልጉትን እንዲያገኙ ይረዳል።",
    careersTitle: "የስራ እድሎች",
    careersSubtitle: "የታመኑ የከተማ ኪራዮችን ከሚገነባው ቡድን ጋር ይቀላቀሉ።",
    careersBody: "ለማህበረሰብ፣ ለተደራሽነት እና ለተሻለ የኪራይ ተሞክሮ የሚጨነቁ ሰዎችን እንፈልጋለን።",
    howItWorksBrowseTitle: "አስስ",
    howItWorksBrowseBody: "ምድቦችን ፈልገው የሚፈልጉትን እቃ ያግኙ።",
    howItWorksBookTitle: "ያስይዙ",
    howItWorksBookBody: "ቀኖችን ይምረጡ እና ኪራይዎን ያረጋግጡ።",
    howItWorksPickupTitle: "ይቀበሉ",
    howItWorksPickupBody: "ከባለቤቱ ጋር ይገናኙ እና ኪራይዎን ይጠቀሙ።",

    // --- About Page ---
    aboutEyebrow: "ስለ ኢስተርን ሲቲስ",
    aboutHeroTitle: "ማህበረሰቦችን በመተማመን ያገናኛል",
    aboutHeroDesc: "ኢስተርን ሲቲስ ጠቃሚ እቃዎች ያሏቸው ሰዎች ከሚፈልጓቸው ሰዎች ጋር - ደህንነቱ ተጠብቆ፣ በተመጣጣኝ ዋጋ እና ወዲያውኑ በምስራቅ ኢትዮጵያ ያገናኛል።",
    aboutMissionTitle: "ተልዕኳችን",
    aboutMissionBody: "ኪራይ ከጓደኛ መበደር ያህል ቀላል እና አስተማማኝ እንዲሆን ማድረግ። በቤትዎ ውስጥ ያልተጠቀሙበት እያንዳንዱ እቃ ገቢ ሊያስገኝ ይችላል ብለን እናምናለን — እያንዳንዱ ተከራይ ደግሞ ሁሉን ሳይገዛ ጥራት ያለው እቃ ሊያገኝ ይገባዋል።",
    aboutWhoWeAreTitle: "እነማን ነን",
    aboutWhoWeAreBody: "ኢስተርን ሲቲስ በጂጂጋ ቀላል ሀሳብ ይዞ ተጀመረ፦ የጋራ ኢኮኖሚ ለምስራቅ ኢትዮጵያ መስራት አለበት። የአካባቢ ቴክኖሎጂ ባለሙያዎች፣ የማህበረሰብ መሪዎች እና ሥራ ፈጣሪዎችን ያቀፈ ቡድን ሆነን በሰዎች መካከል አስተማማኝ የኪራይ መሠረተ ልማት እየገነባን ነው።",
    aboutWhyChooseUs: "ለምን እኛን ይምረጡ",
    aboutBuiltOnValues: "በሚቆጠሩ እሴቶች ላይ የተገነባ",
    aboutTrustTitle: "ዓמינነት እና ደህንነት",
    aboutTrustBody: "እያንዳንዱ ዝርዝር ተረጋግጧል። እያንዳንዱ ተከራይ መታወቂያ ተፈቷል። እያንዳንዱ ግብይት ኢስክሮ ተጠብቋል።",
    aboutCommunityTitle: "ማህበረሰብ ቅድሚያ",
    aboutCommunityBody: "ጎረቤቶችን እናገናኛለን። ትክክለኛ ሰዎች ትክክለኛ እቃዎች ይዘው፣ የአካባቢ ኢኮኖሚ ዕድል ይፈጥራሉ።",
    aboutSpeedTitle: "ፍጥነት እና ምቹነት",
    aboutSpeedBody: "ፈልጉ፣ ያስይዙ፣ ይቀበሉ - በደቂቃዎች ውስጥ። ምንም ወረቀት፣ ምንም መዘግያ።",
    aboutMultilingualTitle: "ብዙ ቋንቋ",
    aboutMultilingualBody: "በእንግሊዝኛ፣ አማርኛ፣ ሶማሊኛ እና አፋን ኦሮሞ ሙሉ ለሙሉ ይገኛል።",
    aboutCoverageEyebrow: "ሽፋናችን",
    aboutCitiesTitle: "የምናገለግላቸው ከተሞች",
    aboutJigjigaDesc: "የሶማሊ ክልል ዋና ከተማ። ትልቁ ገበያችን።",
    aboutDireDawaDesc: "ለመሳሪያ እና ዕቃ ኪራይ ከፍተኛ ፍላጎት ያለው የኢንዱስትሪ ማዕከል።",
    aboutHararDesc: "ታሪካዊ ግንብ ያለው ከተማ። ለዝግጅቶች እና የቤት እቃ ኪራይ ምርጥ።",
    aboutCtaTitle: "ኪራይን ለማዘምን ዝግጁ ነዎት?",
    aboutCtaBody: "ዛሬ በምስራቅ ኢትዮጵያ ኪራይ የሚያደርጉ በሺዎች ለሚቆጠሩ ተረጋግጠው ላሉ አባላት ይቀላቀሉ።",
    aboutCtaGetStarted: "ነፃ ይጀምሩ",
    aboutCtaBrowse: "ዝርዝሮችን ያስሱ",

    // --- Legal / Contact ---
    privacyBody: "ኪራዮችን፣ መልዕክቶችን፣ ማሳወቂያዎችን እና የመድረክ ደህንነትን ለመደገፍ የመለያ እና የቦታ ማስያዣ መረጃን እንጠቀማለን።",
    termsBody: "EasternCityን በመጠቀም ተጠቃሚዎች የኪራይ፣ የክፍያ፣ የስረዛ እና የእቃ መመለሻ ፖሊሲዎችን ለመከተል ይስማማሉ።",
    contactEyebrow: "ያግኙን",
    contactLead: "ለመለያ፣ ለዝርዝር ወይም ለቦታ ማስያዣ እገዛ የEasternCity ድጋፍን ያግኙ።",
    contactLocation: "ጂጂጋ / ድሬዳዋ / ሀረር፣ ኢትዮጵያ",
    fullName: "ሙሉ ስም",
    email: "ኢሜይል",
    message: "መልዕክት",
    sendMessage: "መልዕክት ላክ",
    messageSent: "መልዕክቱ በተሳካ ሁኔታ ተልኳል።",

    // --- Listings / Item Details ---
    browseRentals: "ኪራዮችን ያስሱ",
    availableItems: "ያሉ እቃዎች",
    availableItemsDescription: "ለኪራይ መኪናዎች፣ መሳሪያዎች፣ ኤሌክትሮኒክስ፣ ካሜራዎች፣ የቤት እቃዎች እና የስፖርት እቃዎችን ያግኙ።",
    searchItemsPlaceholder: "እቃዎችን፣ ምድቦችን ወይም ቦታዎችን ፈልግ",
    search: "ፈልግ",
    categoryNotFound: "ምድቡ አልተገኘም",
    categoryNotFoundMessage: "የሚፈልጉት ምድብ አይኖርም።",
    browseAllItems: "ሁሉንም እቃዎች ያስሱ",
    browseAvailableRentalItems: "ያሉ የኪራይ እቃዎችን ያስሱ።",
    itemNotFound: "እቃው አልተገኘም",
    browseItems: "እቃዎችን ያስሱ",
    features: "ባህሪያት",
    rentNow: "አሁን ይከራዩ",
    description: "መግለጫ",
    rentalConditions: "የኪራይ ሁኔታዎች",
    ownerInfo: "የባለቤት መረጃ",
    reviews: "ግምገማዎች",
    similarListings: "ተመሳሳይ ዝርዝሮች",
    requestToBook: "ለማስያዝ ጠይቁ",
    contactOwner: "ባለቤቱን ያናግሩ",
    rentalGuarantee: "የኪራይ ዋስትና",
    paymentMethods: "የክፍያ ዘዴዎች",
    securityDeposit: "የደህንነት ቀጥያ",
    refundableAfterReturn: "ከተመለሰ በኋላ ይመለሳል",
    requiredVerification: "አስፈላጊ ማረጋገጫ",
    nationalId: "ብሔራዊ መታወቂያ (ቀበሌ መታወቂያ)",
    rentalConditionsNote: "እቃው በመጀመሪያ ሁኔታ ተመልሶ መቅረብ አለበት።",
    available: "ይገኛል",
    perDayLabel: "/ቀን",

    // --- Booking Flow ---
    completeYourBooking: "ቦታ ማስያዝዎን ያጠናቅቁ",
    startDate: "መጀመሪያ ቀን",
    endDate: "የመጨረሻ ቀን",
    priceBreakdown: "የዋጋ ዝርዝር",
    serviceFee: "የአገልግሎት ክፍያ (5%)",
    total: "ጠቅላላ",
    continue: "ቀጥል",
    rentalAgreement: "የኪራይ ስምምነት",
    agreeAndContinue: "ተስማማ እና ቀጥል",
    back: "ተመለስ",
    uploadPaymentReceipt: "የክፍያ ደረሰኝ ስቀል",
    submitBooking: "ቦታ ማስያዝ ላክ",
    bookingSubmitted: "ቦታ ማስያዝ ተልኳል! ማረጋገጫ እየጠበቀ ነው።",
    paymentRequired: "ቦታ ማስያዝን ለማጠናቀቅ የክፍያ ቅጽበታዊ ገጽ እይታ ያስፈልጋል።",
    selectDates: "እባክዎ የኪራይ ቀኖችን ይምረጡ።",
    endAfterStart: "የመጨረሻ ቀን ከጀመሩበት ቀን በኋላ መሆን አለበት።",
    acceptRules: "የኪራይ ህጎቹን መቀበል አለብዎት።",
    transferAmount: "እባክዎ ብሩን ያስተላልፉ እና የደረሰኝ ቅጽበታዊ ገጽ እይታ ስቀሉ።",
    cbe: "CBE",
    ebirr: "eBirr",
    telebirr: "Telebirr",
    accountNumber: "የመለያ ቁጥር",

    // --- Dashboard ---
    myListings: "የእኔ ዝርዝሮች",
    myBookings: "የእኔ ቦታ ማስያዞች",
    savedItems: "የተቀመጡ እቃዎች",
    addNewListing: "አዲስ ዝርዝር ጨምር",
    editListing: "ዝርዝር አርትዕ",
    deleteListing: "ዝርዝር ሰርዝ",
    bookingHistory: "የቦታ ማስያዝ ታሪክ",
    activeRentals: "ንቁ ኪራዮች",
    pendingApproval: "ማጽደቅ በመጠባበቅ ላይ",
    approved: "ጸድቋል",
    rejected: "ተቀባይነት አላገኘም",
    awaitingVerification: "ማረጋገጫ በመጠባበቅ ላይ",
    completed: "ተጠናቅቋል",
    cancelled: "ተሰርዟል",
    totalEarnings: "ጠቅላላ ገቢ",
    totalBookings: "ጠቅላላ ቦታ ማስያዞች",
    totalListings: "ጠቅላላ ዝርዝሮች",
    averageRating: "አማካይ ደረጃ",
    recentActivity: "የቅርብ ጊዜ ተግባር",

    // --- Admin ---
    adminPanel: "የአስተዳዳሪ ፓነል",
    superAdminPanel: "የከፍተኛ አስተዳዳሪ ፓነል",
    manageUsers: "ተጠቃሚዎችን አስተዳድር",
    manageListings: "ዝርዝሮችን አስተዳድር",
    manageBookings: "ቦታ ማስያዞችን አስተዳድር",
    reports: "ሪፖርቶች",
    approveItem: "አጽድቅ",
    rejectItem: "አትቀበል",
    suspendUser: "ተጠቃሚ አቁም",
    activateUser: "ተጠቃሚ አንቃ",
    userManagement: "የተጠቃሚ አስተዳደር",
    statistics: "ስታቲስቲክስ",
    systemSettings: "የስርዓት ቅንብሮች",
    platformOverview: "የፕላትፎርም አጠቃላይ ዕይታ",
  },

  so: {
    // --- Nav & General ---
    home: "Bogga Hore",
    categories: "Qaybaha",
    howItWorks: "Sida Ay U Shaqeyso",
    about: "Nagu Saabsan",
    contact: "Xiriir",
    contactUs: "Nala Soo Xiriir",
    items: "Raadi/Daawo Alaabta",
    registerLogin: "Isdiiwaangeli / Gal",
    loginRegister: "Gal / Isdiiwaangeli",
    dashboard: "Dashboard",
    logout: "Ka Bax",
    profile: "Profile",
    messages: "Fariimo",
    language: "Luqad",
    memberSince: "Xubin ka ah",
    myProfile: "Profile-kayga",
    payment: "Lacag-bixin",
    performance: "Waxqabad",
    feedback: "Jawaab-celin",
    notifications: "Ogeysiisyo",
    reviewHistory: "Taariikhda Dib-u-eegista",
    privacySecurity: "Asturnaanta & Amniga",
    settings: "Dejinta",

    // --- Footer ---
    footerTagline: "Suuqa kirada premium-ka ah ee xidha bulshada Jigjiga, Dire Dawa, iyo Harar.",
    ourStory: "Sheekadeena",
    careers: "Shaqooyin",
    privacyPolicy: "Siyaasadda Asturnaanta",
    terms: "Shuruudaha",
    support: "Taageero",
    legal: "Sharci",

    // --- Hero ---
    openMenu: "Fur menu",
    heroEyebrow: "SUUQA KIRO OO LA AAMINAYO",
    heroCta: "Raadi Liisaska",
    heroDiscountOff: "DHIMIS",
    heroFeaturedAlt: "Alaab kiro oo la xushay",
    heroPrevious: "Slide-kii hore",
    heroNext: "Slide-ka xiga",
    heroSlides: "Slide-yada hero",
    heroShowSlide: "Muuji slide",
    heroVehicleTitle: "Ka Kireyso Baabuur iyo Gaadiid Agtaada",
    heroVehicleSubtitle: "Ka daawo kirada gaadiidka milkiilayaasha deegaanka ee la aamini karo.",
    heroElectronicsTitle: "Kireyso Elektaroonik Xaalad Kasta",
    heroElectronicsSubtitle: "Hel laptops, speakers, projectors, qalabka ciyaaraha, iyo wax ka badan.",
    heroToolsTitle: "Qalab Xirfadeed Markaad U Baahato",
    heroToolsSubtitle: "Kireyso qalab iyo agab adigoon qaadin kharashka lahaanshaha.",
    heroCameraTitle: "Kirada Kaamirooyinka Duubis Kasta",
    heroCameraSubtitle: "Qabsado kaamirooyin, lenses, iyo kits munaasabado, content, iyo shaqo hal-abuur leh.",
    heroFurnitureTitle: "Kirada Alaabta Guriga Way Fududaatay",
    heroFurnitureSubtitle: "Kiro alaab guri oo jaban oo loogu talagalay guryo iyo munaasabado.",
    heroSportsTitle: "Qalabka Ciyaaraha Waa Diyaar Markaad Diyaar Tahay",
    heroSportsSubtitle: "Kireyso baaskiillo, golf sets, kayaks, qalabka fuulista, iyo qalabka dibadda.",

    // --- Search & Categories ---
    allItems: "Dhammaan Alaabta",
    usedItems: "Alaab La Isticmaalay",
    newItems: "Alaab Cusub",
    category: "Qayb",
    allCategories: "Dhammaan Qaybaha",
    electronics: "Elektaroonik",
    tools: "Qalab",
    vehicles: "Gaadiid",
    cameras: "Kaamirooyin",
    sports: "Ciyaaro",
    furniture: "Alaab Guri",
    maxPrice: "Qiimaha Ugu Badan",
    maxPriceTitle: "Qiimaha ugu badan maalintii ETB",
    perDay: "maalin",
    searchRentals: "Raadi Kiro",
    trustedRentalService: "ADEEG KIRO OO LA AAMINAYO",
    exploreAllItems: "Daawo Dhammaan Alaabta",
    allStatus: "Dhammaan Xaaladaha",
    featured: "La Xushay",
    rentalItem: "Alaab Kiro",
    viewDetails: "Daawo Faahfaahin",
    compare: "Isbarbar dhig",
    wishlist: "Liiska rabitaanka",
    similar: "La mid ah",
    suv: "SUV",
    camera: "Kaamiro",
    events: "Munaasabado",
    petrol: "Batrool",
    kit: "Kit",
    cordless: "Xadhig la'aan",
    likeNew: "Sida Cusub",
    westside: "Galbeed",
    downtown: "Bartamaha Magaalada",
    midtown: "Bartamaha",
    north: "Waqooyi",
    eastEnd: "Bari",
    auto: "Auto",
    anyCondition: "Xaalad Kasta",
    used: "La Isticmaalay",
    location: "Goob",
    allCities: "Dhammaan Magaalooyinka",
    findRentals: "Raadi Kiro",
    sefar: "Xaafad",
    allSefar: "Dhammaan Xaafadaha",
    neighbourhood: "Xaafad",

    // --- About / How It Works ---
    ourStoryTitle: "Sheekadeena",
    ourStorySubtitle: "EasternCity waxay dadka ku xirtaa alaab kiro oo deegaanka ah oo la isku halleyn karo.",
    ourStoryBody: "Madalkayagu wuxuu ka caawiyaa milkiilayaasha inay liis gareeyaan alaab waxtar leh, kiraystayaashana inay helaan waxa ay u baahan yihiin iyagoon iibsan.",
    careersTitle: "Shaqooyin",
    careersSubtitle: "Ku biir kooxda dhisaysa kiro magaalo oo la isku halleyn karo.",
    careersBody: "Waxaan raadineynaa dad daneeya bulshada, helitaanka, iyo khibrad kiro oo wanaagsan.",
    howItWorksBrowseTitle: "Daawo",
    howItWorksBrowseBody: "Raadi qaybaha oo hel alaabta aad u baahan tahay.",
    howItWorksBookTitle: "Qabso",
    howItWorksBookBody: "Dooro taariikhaha oo xaqiiji kiradaada.",
    howItWorksPickupTitle: "Qaado",
    howItWorksPickupBody: "La kulan milkiilaha oo ku raaxayso kiradaada.",

    // --- About Page ---
    aboutEyebrow: "KU SAABSAN EASTERNCITIES",
    aboutHeroTitle: "Bulshada Ku Xidaysa Aaminaad",
    aboutHeroDesc: "EasternCities waxay isku xirtaa dadka leh alaab waxtar leh iyo dadka u baahan - si amaan ah, qiimo jaban, oo degdeg ah oo ku saabsan Bariga Itoobiya.",
    aboutMissionTitle: "Hadafkayaga",
    aboutMissionBody: "Kiro u dhig mid la aamin karo oo fudud sida saaxiib aad ka amaanato. Waxaan aaminaynaa in alaab kasta oo gurigaaga ku fadhiyo lacag wax soo saari karto — kiraystayaashuna waxay mudan yihiin helitaanka alaab tayo leh iyagoon iibsan.",
    aboutWhoWeAreTitle: "Cidda Aynnu Nahay",
    aboutWhoWeAreBody: "EasternCities waxaa lagu aasaasay Jigjiga fikrad fudud: dhaqaalaha wadaagga waa inuu u shaqeeyaa Bariga Itoobiya. Waxaan nahay koox teknolojiyiyin, hoggaamiyayaasha bulshada, iyo ganacsatada dhisaysa kaabayaasha kiro ee la aaminsan.",
    aboutWhyChooseUs: "MAXAA NOOGU DOORANAYSAA",
    aboutBuiltOnValues: "Ku Dhisan Qiyamka Muhiimka ah",
    aboutTrustTitle: "Aaminaad & Amniga",
    aboutTrustBody: "Liiska kasta waa la xaqiijiyay. Kiraystaha kasta waa laga hujoodiyay. Macaamilada kasta waa escrow-lagu ilaaliyay.",
    aboutCommunityTitle: "Bulsho Marka Hore",
    aboutCommunityBody: "Naabaddayaasha waan ku xidnaa. Dad dhabta ah oo leh alaab dhab ah, oo dhisaya fursadda dhaqaale ee deegaanka.",
    aboutSpeedTitle: "Xawaare & Fudayd",
    aboutSpeedBody: "Raadi, qabso, oo hel - daqiiqado gudahood. Warqad ma loo baahna, dib u dhac ma jiro.",
    aboutMultilingualTitle: "Luqado Badan",
    aboutMultilingualBody: "Si buuxda ugu heli kartaa Ingiriisi, Amxaari, Soomaali, iyo Afaan Oromo.",
    aboutCoverageEyebrow: "DABOOLKAYAGA",
    aboutCitiesTitle: "Magaalooyinka Aan U Adeegno",
    aboutJigjigaDesc: "Caasimadda Gobolka Soomaalida. Suuqayaga ugu weyn.",
    aboutDireDawaDesc: "Xarunta warshadaha oo leh baahi sare oo kirada qalab iyo tirakoobka.",
    aboutHararDesc: "Magaalo taariikhiga ah oo leh gidaar. Ku habboon munaasabadaha iyo kirada alaabta guriga.",
    aboutCtaTitle: "Diyaar Maad u Tahay Inaad Si Caqli-gal ah Kireyso?",
    aboutCtaBody: "Ku biir xubno la xaqiijiyay oo kumanyaal ah oo maanta ku kireysta Bariga Itoobiya.",
    aboutCtaGetStarted: "Bilow Bilaash",
    aboutCtaBrowse: "Daawo Liisaska",

    // --- Legal / Contact ---
    privacyBody: "Waxaan u isticmaalnaa macluumaadka akoonka iyo booking-ka si aan u taageerno kirada, fariimaha, ogeysiisyada, iyo badbaadada madalka.",
    termsBody: "Marka la isticmaalo EasternCity, isticmaalayaashu waxay oggolaanayaan inay raacaan siyaasadaha kirada, lacag bixinta, baajinta, iyo soo celinta alaabta.",
    contactEyebrow: "XIRIIR",
    contactLead: "La xiriir taageerada EasternCity si aad uga hesho caawimaad akoon, liis, ama booking.",
    contactLocation: "Jigjiga / Dire Dawa / Harar, Ethiopia",
    fullName: "Magaca Buuxa",
    email: "Email",
    message: "Fariin",
    sendMessage: "Dir Fariin",
    messageSent: "Fariinta si guul leh ayaa loo diray.",

    // --- Listings / Item Details ---
    browseRentals: "Daawo Kirooyinka",
    availableItems: "Alaabta La Heli Karo",
    availableItemsDescription: "Hel gaadiid, qalab, elektaroonik, kaamirooyin, alaab guri, iyo qalab ciyaaro oo kiro ah.",
    searchItemsPlaceholder: "Raadi alaab, qaybo, ama goobaha",
    search: "Raadi",
    categoryNotFound: "Qayb Lama Helin",
    categoryNotFoundMessage: "Qaybta aad raadinayso ma jirto.",
    browseAllItems: "Daawo Dhammaan Alaabta",
    browseAvailableRentalItems: "Daawo alaabta kirada ee la heli karo.",
    itemNotFound: "Alaabta lama helin",
    browseItems: "Daawo Alaabta",
    features: "Astaamaha",
    rentNow: "Hadda Kireyso",
    description: "Sharaxaad",
    rentalConditions: "Shuruudaha Kirada",
    ownerInfo: "Macluumaadka Milkiilaha",
    reviews: "Dib-u-eegis",
    similarListings: "Liisaska La mid ah",
    requestToBook: "Codso Qabsasho",
    contactOwner: "La Xiriir Milkiilaha",
    rentalGuarantee: "Dammaanad Kiro",
    paymentMethods: "Hababka Lacag-bixinta",
    securityDeposit: "Kaydka Amniga",
    refundableAfterReturn: "La soo celin karaa ka dib soo celinta",
    requiredVerification: "Xaqiijinta Lagama Maarmaanka ah",
    nationalId: "Aqoonsiga Qaranka (Kebele ID)",
    rentalConditionsNote: "Alaabta si asalka ah ayaa loo soo celin doonaa.",
    available: "La Heli Karo",
    perDayLabel: "/maalin",

    // --- Booking Flow ---
    completeYourBooking: "Dhammaystir Qabsashadaada",
    startDate: "Taariikhda Bilowga",
    endDate: "Taariikhda Dhamaadka",
    priceBreakdown: "Faahfaahinta Qiimaha",
    serviceFee: "Kharashka Adeegga (5%)",
    total: "Wadarta",
    continue: "Sii wad",
    rentalAgreement: "Heshiiska Kirada",
    agreeAndContinue: "Ogolow & Sii wad",
    back: "Dib u noqo",
    uploadPaymentReceipt: "Soo geli Rasiidka Lacag-bixinta",
    submitBooking: "Gudbi Qabsashada",
    bookingSubmitted: "Qabsashadii la gudbiyay! Xaqiijin la sugayaa.",
    paymentRequired: "Sawir rasiidka lacag-bixinta ayaa loo baahan yahay.",
    selectDates: "Fadlan dooro taariikhaha kirada.",
    endAfterStart: "Taariikhda dhamaadka waa inay ka dambeysaa taariikhda bilowga.",
    acceptRules: "Waa inaad oggolaataa xeerarka kirada.",
    transferAmount: "Fadlan u gudbi lacagta oo soo geli sawirka rasiidka.",
    cbe: "CBE",
    ebirr: "eBirr",
    telebirr: "Telebirr",
    accountNumber: "Lambarka Akoonka",

    // --- Dashboard ---
    myListings: "Liisaskaygii",
    myBookings: "Qabsashadaydii",
    savedItems: "Alaabta La Keydsaday",
    addNewListing: "Ku dar Liis Cusub",
    editListing: "Wax ka beddel Liiska",
    deleteListing: "Tirtir Liiska",
    bookingHistory: "Taariikhda Qabsashada",
    activeRentals: "Kirado Firfircoon",
    pendingApproval: "La sugayaa Ogolaanshaha",
    approved: "La Ansixiyay",
    rejected: "La Diiday",
    awaitingVerification: "La sugayaa Xaqiijinta",
    completed: "La Dhammaystay",
    cancelled: "La Baajiyay",
    totalEarnings: "Wadarta Dakhliga",
    totalBookings: "Wadarta Qabsashadaha",
    totalListings: "Wadarta Liisaska",
    averageRating: "Celceliska Darajooyinka",
    recentActivity: "Hawlaha Dhawaan",

    // --- Admin ---
    adminPanel: "Panelka Maamulka",
    superAdminPanel: "Panelka Maamulka Sare",
    manageUsers: "Maamul Isticmaalayaasha",
    manageListings: "Maamul Liisaska",
    manageBookings: "Maamul Qabsashadaha",
    reports: "Warbixinno",
    approveItem: "Ogolow",
    rejectItem: "Diid",
    suspendUser: "Jooji Isticmaalaha",
    activateUser: "Firfircoon Isticmaalaha",
    userManagement: "Maamulka Isticmaalayaasha",
    statistics: "Xogta",
    systemSettings: "Dejinta Nidaamka",
    platformOverview: "Dulmarinta Madalka",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem("language") || "en",
  );

  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem("language", language);
  }, [language]);

  const t = useCallback((key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t,
      translations,
    }),
    [language, t],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }

  return context;
}
