import { useEffect, useState } from "react";
import { adminApi } from "../../services/adminManagementService.js";

export default function AdminAnalyticsPage() {
  const [filter, setFilter] = useState("month");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [data, setData] = useState({ userGrowth: 0, listingGrowth: 0, listingFeeRevenue: 0, promoRevenue: 0, verifications: 0, cityStats: [] });
  useEffect(() => { adminApi.analytics({ range: filter, from: startDate, to: endDate }).then(setData).catch(console.error); }, [filter, startDate, endDate]);
  const handleCustomSearch = (e) => { e.preventDefault(); setFilter("custom"); };
  return <main className="dashboard-content"><div className="d-flex justify-content-between align-items-center mb-4"><div><span className="section-label">ADMIN</span><h1 className="h3 mb-0">Platform Analytics</h1><p className="text-muted mb-0">Analyze platform growth metrics and rental activities.</p></div></div><div className="admin-table-container mb-4"><div className="d-flex flex-wrap align-items-center justify-content-between gap-3"><div className="d-flex gap-2">{["today", "week", "month", "year"].map(opt => <button key={opt} type="button" className={`btn btn-sm ${filter === opt ? "btn-accent-custom" : "btn-outline-secondary"}`} onClick={() => setFilter(opt)}>{opt.toUpperCase()}</button>)}</div><form onSubmit={handleCustomSearch} className="d-flex align-items-center gap-2"><span className="text-muted"><small>Custom:</small></span><input type="date" className="form-control form-control-sm" value={startDate} onChange={e => { setStartDate(e.target.value); setFilter("custom"); }} required /><span className="text-muted"><small>to</small></span><input type="date" className="form-control form-control-sm" value={endDate} onChange={e => { setEndDate(e.target.value); setFilter("custom"); }} required /></form></div></div><div className="row"><Metric label="User Growth" value={`+${data.userGrowth}`} icon="bi-people" tone="primary" /><Metric label="Listing Growth" value={`+${data.listingGrowth}`} icon="bi-box-seam" tone="success" /><Metric label="Listing Fee Revenue" value={`${Number(data.listingFeeRevenue || 0).toLocaleString()} ETB`} icon="bi-receipt" tone="warning" /><Metric label="Promotion Revenue" value={`${Number(data.promoRevenue || 0).toLocaleString()} ETB`} icon="bi-cash-stack" tone="danger" /><Metric label="Verifications" value={data.verifications} icon="bi-shield-check" tone="info" /></div><div className="row"><div className="col-12"><div className="admin-table-container"><h2 className="h5 mb-3 d-flex align-items-center gap-2"><i className="bi bi-geo text-primary-custom" /> City Statistics Performance</h2><div className="table-responsive"><table className="table align-middle"><thead><tr><th>City</th><th>New Listings</th><th>New Rentals</th><th>Engagement Rate</th></tr></thead><tbody>{(data.cityStats || []).map(c => <tr key={c.city}><td className="fw-bold">{c.city}</td><td>+{c.listings} listings</td><td>+{c.rentals} rentals</td><td><div className="d-flex align-items-center gap-2"><div className="progress w-100" style={{ height: "6px" }}><div className="progress-bar bg-danger" style={{ width: `${Math.min(100, Math.round((c.rentals / (c.listings || 1)) * 100))}%` }} /></div><small className="fw-bold">{Math.min(100, Math.round((c.rentals / (c.listings || 1)) * 100))}%</small></div></td></tr>)}</tbody></table></div></div></div></div></main>;
}
function Metric({ label, value, icon, tone }) { return <div className="col-md-3 mb-4"><div className="admin-stat-card d-flex align-items-center gap-3 p-4 rounded shadow-sm" style={{ background: "var(--card-bg)" }}><div className={`stat-icon-wrapper bg-${tone}-subtle text-${tone} p-3 rounded`}><i className={`bi ${icon}`} style={{ fontSize: "1.5rem" }} /></div><div><span className="text-muted"><small>{label}</small></span><h2 className="mb-0 fw-bold">{value}</h2></div></div></div>; }
