import { useEffect, useState } from "react";
import StatusBadge from "../../components/common/StatusBadge.jsx";
import { adminApi, formatDate } from "../../services/adminManagementService.js";

export default function AdminBookingsPage() {
  const [bookings, setBookings] = useState([]);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("all");
  useEffect(() => { adminApi.bookings({ search, status: filter }).then(setBookings).catch(console.error); }, [search, filter]);
  return <main className="dashboard-content"><div className="d-flex justify-content-between align-items-center mb-4"><div><span className="section-label">ADMIN</span><h1 className="h3 mb-0">Bookings Management</h1><p className="text-muted mb-0">Monitor platform rental bookings. Payments are arranged directly between renters and owners.</p></div></div><div className="admin-table-container"><div className="d-flex flex-wrap justify-content-between gap-3 mb-4"><div className="d-flex gap-2">{["all", "pending", "accepted", "active", "completed", "cancelled"].map(opt => <button key={opt} type="button" className={`btn btn-sm ${filter === opt ? "btn-accent-custom" : "btn-outline-secondary"}`} onClick={() => setFilter(opt)}>{opt.toUpperCase()}</button>)}</div><div className="search-box" style={{ maxWidth: "300px", width: "100%" }}><input type="text" placeholder="Search by ID, item, renter..." className="form-control" value={search} onChange={e => setSearch(e.target.value)} /></div></div><div className="table-responsive"><table className="table table-hover align-middle"><thead><tr><th>Booking ID</th><th>Item</th><th>Renter</th><th>Dates</th><th>Duration</th><th>Status</th></tr></thead><tbody>{bookings.map(b => <tr key={b.id}><td className="fw-bold">{b.id}</td><td>{b.listing?.title || "-"}</td><td>{b.renter?.name || b.renter?.email || "-"}</td><td><div><small>{formatDate(b.startDate)} to</small></div><div><small>{formatDate(b.endDate)}</small></div></td><td className="text-muted">{Math.max(1, Math.ceil((new Date(b.endDate) - new Date(b.startDate)) / (1000*60*60*24)))} day(s)</td><td><StatusBadge status={b.status} /></td></tr>)}{bookings.length === 0 && <tr><td colSpan="6" className="text-center text-muted py-4">No bookings found matching criteria.</td></tr>}</tbody></table></div></div></main>;
}
