import { useState, useEffect } from "react";
import StatusBadge from "../../components/common/StatusBadge.jsx";
import { adminApi, formatDate } from "../../services/adminManagementService.js";

export default function AdminListingManagementPage() {
  const [listings, setListings] = useState([]);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("all");
  const [editingItem, setEditingItem] = useState(null);
  const [viewScreenshot, setViewScreenshot] = useState(null);
  const [notice, setNotice] = useState("");
  const [isLoading, setIsLoading] = useState(true);

  const refreshListings = async () => setListings(await adminApi.listings({ search, status: filter === "all" ? "" : filter }));
  useEffect(() => { refreshListings().catch(console.error); }, [search, filter]);

  const handleStatusChange = async (id, newStatus, reason = "") => { await adminApi.updateListing(id, { status: newStatus, rejectionReason: reason }); await refreshListings(); };
  const handleRemove = async (id) => { if (confirm("Are you sure you want to remove this listing?")) { await adminApi.deleteListing(id); await refreshListings(); } };
  const handleSaveEdit = async (e) => { e.preventDefault(); await adminApi.updateListing(editingItem.id, { title: editingItem.title, city: editingItem.city, location: editingItem.location, pricePerDay: editingItem.pricePerDay }); setEditingItem(null); await refreshListings(); };

  return (
    <main className="dashboard-content"><div className="d-flex justify-content-between align-items-center mb-4"><div><span className="section-label">ADMIN</span><h1 className="h3 mb-0">Listings Management</h1><p className="text-muted mb-0">Approve new listings, reject invalid entries, or edit listing info.</p></div></div>
      <div className="admin-table-container"><div className="d-flex flex-wrap justify-content-between gap-3 mb-4"><div className="d-flex gap-2">{["all", "under_review", "published", "rejected"].map(opt => <button key={opt} type="button" className={`btn btn-sm ${filter === opt ? "btn-accent-custom" : "btn-outline-secondary"}`} onClick={() => setFilter(opt)}>{opt.replace("_", " ").toUpperCase()}</button>)}</div><div className="search-box" style={{ maxWidth: "300px", width: "100%" }}><input type="text" placeholder="Search listings..." className="form-control" value={search} onChange={e => setSearch(e.target.value)} /></div></div>
        <div className="table-responsive"><table className="table table-hover align-middle"><thead><tr><th>Item Name</th><th>Category</th><th>City</th><th>Owner</th><th>Submitted</th><th>Screenshot</th><th>Status</th><th>Actions</th></tr></thead><tbody>{listings.map(item => { const status = String(item.status || "PENDING").toLowerCase(); return <tr key={item.id}><td className="fw-bold">{item.title}</td><td>{item.category?.name || "-"}</td><td>{item.city}</td><td>{item.owner?.name || item.owner?.email || "-"}</td><td>{formatDate(item.createdAt)}</td><td>{item.paymentProofUrl ? <button className="btn btn-sm btn-outline-secondary" onClick={() => setViewScreenshot(item.paymentProofUrl)}>View</button> : <span className="text-muted small">None</span>}</td><td><StatusBadge status={item.status} /></td><td><div className="d-flex gap-2">{["pending", "under_review", "pending approval", "rejected"].includes(status) && <><button type="button" className="btn btn-sm btn-success" onClick={() => handleStatusChange(item.id, "APPROVED")}>Approve</button><button type="button" className="btn btn-sm btn-outline-warning" onClick={() => { const reason = prompt("Enter rejection reason:"); if (reason) handleStatusChange(item.id, "REJECTED", reason); }}>Reject</button></>}<button type="button" className="btn btn-sm btn-outline-info" onClick={() => setEditingItem(item)}>Edit</button><button type="button" className="btn btn-sm btn-outline-danger" onClick={() => handleRemove(item.id)}>Remove</button></div></td></tr>; })}{listings.length === 0 && <tr><td colSpan="8" className="text-center text-muted py-4">No listings found matching criteria.</td></tr>}</tbody></table></div>
      </div>
      {viewScreenshot && <div className="modal show d-block" style={{ backgroundColor: "rgba(0,0,0,0.5)" }}><div className="modal-dialog modal-dialog-centered"><div className="modal-content" style={{ background: "var(--card-bg)" }}><div className="modal-header border-0"><h5 className="modal-title">Payment Screenshot</h5><button type="button" className="btn-close" onClick={() => setViewScreenshot(null)} /></div><div className="modal-body text-center"><img src={viewScreenshot} alt="Payment Screenshot" className="img-fluid rounded" /></div></div></div></div>}
      {editingItem && <div className="modal show d-block" style={{ backgroundColor: "rgba(0,0,0,0.5)" }}><div className="modal-dialog modal-dialog-centered"><div className="modal-content" style={{ background: "var(--card-bg)" }}><form onSubmit={handleSaveEdit}><div className="modal-header border-0"><h5 className="modal-title">Edit Listing Details</h5><button type="button" className="btn-close" onClick={() => setEditingItem(null)} /></div><div className="modal-body"><div className="mb-3"><label className="form-label">Item Title</label><input type="text" className="form-control" value={editingItem.title || ""} onChange={e => setEditingItem({ ...editingItem, title: e.target.value })} required /></div><div className="mb-3"><label className="form-label">Category</label><input type="text" className="form-control" value={editingItem.category?.name || ""} readOnly /></div><div className="row"><div className="col-md-6 mb-3"><label className="form-label">City</label><input type="text" className="form-control" value={editingItem.city || ""} onChange={e => setEditingItem({ ...editingItem, city: e.target.value })} required /></div><div className="col-md-6 mb-3"><label className="form-label">Sefar</label><input type="text" className="form-control" value={editingItem.location || ""} onChange={e => setEditingItem({ ...editingItem, location: e.target.value })} /></div></div></div><div className="modal-footer border-0"><button type="button" className="btn btn-secondary" onClick={() => setEditingItem(null)}>Cancel</button><button type="submit" className="btn btn-accent-custom">Save Changes</button></div></form></div></div></div>}
    </main>
  );
}
